#!/bin/bash

# Set up the directory
BENCH_DIR="$HOME/competitor_bench/Membase"
rm -rf "$BENCH_DIR"
mkdir -p "$BENCH_DIR"
#exec > "$BENCH_DIR/full_bench.log" 2>&1

# Horrible but working way of finding the argument after --email.
email="$(perl -e 'use List::Util qw(first); my $email_idx = 1 + first { $ARGV[$_] eq "--email" } 0 .. $#ARGV; print $ARGV[$email_idx]' -- "$@")"

# Build the stress client
cd bench/stress-client
make
scp stress dr-doom:/home/teapot/stress
cd ../dbench

# Some helper functions
function delete_database_files() { # They are large and useless.
    rm -rf "$(find "$BENCH_DIR" -name membase_data_tmp)"
}


SSD_DRIVES="-f /dev/sdb -f /dev/sdc -f /dev/sdd -f /dev/sde"
HDD_DRIVES="" # TODO

SERVER_HOSTS="magneto,magneto2"
CANONICAL_CLIENTS="512"
CANONICAL_DURATION="60s"

DATABASE="membase"

# TODO: Can we use SSDs? Would that make sense (maybe not)?
MEMBASE_DATA_PATH="membase_data_tmp"


echo "To get the canonical hardware, we have to disable all but 12 CPUs."
echo 'Please give me authorization to run sh -c "for CPU in 12 13 14 15 16 17 18 19 20 21 22 23; do echo 0 > /sys/devices/system/cpu/cpu\$CPU/online; done"'
sudo sh -c "for CPU in 12 13 14 15 16 17 18 19 20 21 22 23; do echo 0 > /sys/devices/system/cpu/cpu\$CPU/online; done"

# Run workloads
for WORKLOAD in ../workloads/*; do
    if [ -d "$WORKLOAD" ]; then
        echo -e "\n\E[37;44m\033[1m<----- Running workload in $WORKLOAD ----->\033[0m\n"
        export BENCH_DIR
        export SSD_DRIVES
        export HDD_DRIVES
        export DATABASE
        export SERVER_HOSTS
        export CANONICAL_CLIENTS
        export CANONICAL_DURATION
        export MEMBASE_DATA_PATH
    
        if [ -e "$WORKLOAD/Setup" ]; then
            "$WORKLOAD/Setup"
        fi
        
        for CONFIGURATION in $( find "$WORKLOAD" -type f -name "R*" | sort ); do
            echo -e "\n\033[1mRunning $CONFIGURATION\033[0m"
            if [ -e "$BENCH_DIR/environment" ]; then
                . "$BENCH_DIR/environment"
            fi
            $CONFIGURATION
        done
        
        if [ -e "$WORKLOAD/Teardown" ]; then
            if [ -e "$BENCH_DIR/environment" ]; then
                . "$BENCH_DIR/environment"
            fi
            "$WORKLOAD/Teardown"
        fi
        
        if [ -e "$BENCH_DIR/environment" ]; then
            rm -f "$BENCH_DIR/environment"
        fi
    fi
done

echo "We can turn on the CPUs again now..."
echo 'Please give me authorization to run sh -c "for CPU in 12 13 14 15 16 17 18 19 20 21 22 23; do echo 1 > /sys/devices/system/cpu/cpu\$CPU/online; done"'
sudo sh -c "for CPU in 12 13 14 15 16 17 18 19 20 21 22 23; do echo 1 > /sys/devices/system/cpu/cpu\$CPU/online; done"


# Now that all benchmarks are done, delete any database files that might have been left over
delete_database_files
