#!/bin/bash

# Set up the directory
BENCH_DIR="$HOME/competitor_bench/Membase"
rm -rf "$BENCH_DIR"
mkdir -p "$BENCH_DIR"
exec > "$BENCH_DIR/full_bench.log" 2>&1

# Horrible but working way of finding the argument after --email.
email="$(perl -e 'use List::Util qw(first); my $email_idx = 1 + first { $ARGV[$_] eq "--email" } 0 .. $#ARGV; print $ARGV[$email_idx]' -- "$@")"

# Build the stress client
cd bench/stress-client
make
scp stress dr-doom:/home/teapot/stress
cd ../dbench

# Some helper functions
function delete_database_files() { # They are large and useless.
    rm -rf "$(find "$BENCH_DIR" -name membase_data)"
}

# Membase:

# Canonical workload on the canonical setup
./dbench -p 11211                                                                             \
    -d "$BENCH_DIR/bench_output/Canonical_workload_on_canonical_hardware" -H 10.0.0.2 \
    {server}membase:"-d membase_data -m 32768"                                                \
    {client}stressfree[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'                           \
    iostat:1 vmstat:1

# Out of RAM performance

# Minimum Membase cache size is 256MB.
# I/O bound performance
./dbench -p 11211                                                       \
    -d "$BENCH_DIR/bench_output/SSD_IO_performance" -H 10.0.0.2 \
    {server}membase:"-d membase_data -m 256"                            \
    {client}stressfree[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'     \
    iostat:1 vmstat:1

# Store keys in temporary file.
TMP_KEY_FILE="$(ssh dr-doom mktemp)"

PERSISTENT_DATA_DIR="$BENCH_DIR/membase_data"

# Pure inserts performance
./dbench -p 11211                                                                               \
    -d "$BENCH_DIR/bench_output/Pure_inserts_on_canonical_hardware" -H 10.0.0.2                 \
    {server}membase:"-d $PERSISTENT_DATA_DIR -m 32768"                                          \
    {client}stressfree[dr-doom:/home/teapot/stress]:"-c 512 -w 0/0/1/0 -o $TMP_KEY_FILE -d 60s" \
    iostat:1 vmstat:1

# Pure selects performance (run right after insert without recreating the database)
./dbench -p 11211                                                                               \
    -d "$BENCH_DIR/bench_output/Pure_selects_on_canonical_hardware" -H 10.0.0.2                 \
    {server}membase:"-d $PERSISTENT_DATA_DIR -m 32768"                                          \
    {client}stressfree[dr-doom:/home/teapot/stress]:"-c 512 -w 0/0/0/1 -i $TMP_KEY_FILE -d 60s" \
    iostat:1 vmstat:1

# Delete temporary key file.
ssh dr-doom -- rm "$TMP_KEY_FILE"

# Core/CPU scalability
# Concurrent clients scalability
# Canonical workload on HDD performance

# Durability settings performance
# TODO: Figure out Membase durability.
#./dbench                                                                              \
#    -d "$BENCH_DIR/bench_output/Strong_durability_performance" -H 10.0.0.2            \
#    {server}rethinkdb:"--wait-for-flush y --flush-timer 2 -c 12 -m 32768 $SSD_DRIVES" \
#    {client}stressfree[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'                   \
#    iostat:1 vmstat:1 rdbstat:1

# Now that all benchmarks are done, delete any database files that might have been left over
delete_database_files
