#!/bin/bash

if [ $DATABASE == "rethinkdb" ]; then
    ../../build/release/rethinkdb create $SSD_DRIVES --force
fi

# This workload needs to run its own Python script remotely because
# its workload cannot be expressed as a stress-client command line. We manually copy the
# custom stress client to puzzler.
scp ../workloads/canonicalPlusSmallRgets/rgetStressClient.py puzzler:/home/teapot/rgetStressClient.py
export RGET_STRESS_CLIENT="puzzler:/home/teapot/rgetStressClient.py"

export -p > "$BENCH_DIR/environment"
