// Autogenerated by convert_protofile.py.
// Do not edit this file directly.
// The template for this file is located at:
// ../../../../../../../templates/Enum.java
package com.rethinkdb.proto;

public enum FrameType {

    POS(1),
    OPT(2);

    public final int value;

    private FrameType(int value){
        this.value = value;
    }
}
