// Autogenerated by convert_protofile.py.
// Do not edit this file directly.
// The template for this file is located at:
// ../../../../../../../templates/Enum.java
package com.rethinkdb.proto;

public enum Protocol {

    PROTOBUF(656407617),
    JSON(2120839367);

    public final int value;

    private Protocol(int value){
        this.value = value;
    }
}
