#!/bin/bash

# Out of RAM performance
# SSD I/O bound performance

./dbench                                                                \
    -d "$BENCH_DIR/bench_output/SSD_IO_performance" -H magneto,magneto2 \
    {server}rethinkdb:"-c 12 -m 0 $SSD_DRIVES"                          \
    {client}stress[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'         \
    iostat:1 vmstat:1 rdbstat:1
