#!/bin/bash

# Unmount the fs (might fail, that's ok)
echo sudo -S umount $3
echo $1 | sudo -S umount $3

# Create the filesystem
echo sudo -S mke2fs -t ext2 -q $2
echo $1 | sudo -S mke2fs -t ext2 -q -F $2

# Mount the filesystem
echo sudo -S mount -t ext2 $2 $3
echo $1 | sudo -S mount -t ext2 $2 $3

# Create the file
echo sudo -S dd if=/dev/zero of=$4 bs=1024 count=$5
echo $1 | sudo -S dd if=/dev/zero of=$4 bs=1024 count=$5

