Document: rethinkdb
Title: Debian rethinkdb Manual
Author: <insert document author here>
Abstract: This manual describes what rethinkdb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rethinkdb/rethinkdb.sgml.gz

Format: postscript
Files: /usr/share/doc/rethinkdb/rethinkdb.ps.gz

Format: text
Files: /usr/share/doc/rethinkdb/rethinkdb.text.gz

Format: HTML
Index: /usr/share/doc/rethinkdb/html/index.html
Files: /usr/share/doc/rethinkdb/html/*.html
