#!/bin/bash

echo
echo "*****************************************"
echo "*** Checking unit tests before commit ***"
echo "*****************************************"
echo

cd test/
retest clean

if retest
then
        echo
        echo "***************************************"
        echo "*** All tests passed, committing :) ***"
        echo "***************************************"
        echo
else
        echo
        echo "*********************************************"
        echo "*** Some tests failed, aborting commit :( ***"
        echo "*********************************************"
        echo
        exit -1
fi
