#!/bin/sh
set -e

case "$1" in
  remove|upgrade|deconfigure|failed-upgrade)
    rm -f /etc/init/rethinkdb.conf
    ;;
  *)
    echo "Warning: RethinkDB postrm script called with unknown set of arguments: $*"
    ;;
esac
