#!/bin/sh
set -e

bin_dir=BIN_DIR
server_exec_name=SERVER_EXEC_NAME
server_exec_name_versioned=SERVER_EXEC_NAME_VERSIONED

case "$1" in
  remove|upgrade|deconfigure|failed-upgrade)
    update-alternatives --remove $server_exec_name $bin_dir/$server_exec_name_versioned
    ;;
  update-rc.d rethinkdb remove ;
  /etc/init.d/rethinkdb stop ;
  *)
    echo "Warning: RethinkDB prerm script called with unknown set of arguments: $*"
    ;;
esac

