#!/bin/bash

if [ $DATABASE == "rethinkdb" ]; then
    ../../build/release/rethinkdb create $SSD_DRIVES --force
fi

# The rget workload needs to run its own Python script remotely because
# its workload cannot be expressed as a stress-client command line. We manually copy the
# custom stress client to puzzler.
scp ../workloads/rgetMix/rgetMixStressClient.py puzzler:/home/teapot/rgetMixStressClient.py
export RGET_STRESS_CLIENT="puzzler:/home/teapot/rgetMixStressClient.py"

export -p > "$BENCH_DIR/environment"

