#!/bin/bash

mkdir -p "$BENCH_DIR/bench_output/Range_read_mix"
. `dirname "$0"`/DESCRIPTION_RUN > "$BENCH_DIR/bench_output/Range_read_mix/DESCRIPTION_RUN"

if [ $DATABASE == "rethinkdb" ]; then
    . `dirname "$0"`/DESCRIPTION > "$BENCH_DIR/bench_output/Range_read_mix/DESCRIPTION"
fi
