#!/bin/bash
. `cd -P -- "$(dirname $0)" && pwd -P`/init.sh

poc=${1-$POC}
shift
offset=${1-1}
shift
staging=${1-$STAGING}
shift
rethbin=$staging/.persist/rethinkdb
ssh_to "$poc" "$rethbin admin --join localhost:$((CLUSTER_PORT+offset)) $@"
