#!/bin/bash
. `cd -P -- "$(dirname $0)" && pwd -P`/init.sh
rethbin=$RETHINKDB_FOR_ADMIN
if [[ ! -e $rethbin ]]; then
    echo "ERROR: requires $rethbin to point to valid rethinkdb binary." >&2
    exit 1
fi
$RETHINKDB_FOR_ADMIN admin --join localhost:$ADMIN_CLUSTER_PORT "$@"
