#!/bin/bash
. `cd -P -- "$(dirname $0)" && pwd -P`/init.sh
rethbin=./rethinkdb_for_admin
if [[ ! -e $rethbin ]]; then
    echo "ERROR: requires $rethbin to point to valid rethinkdb binary." >&2
    exit 1
fi
./rethinkdb_for_admin admin --join localhost:`cat cluster_port` "$@"
