#!/bin/bash
. `cd -P -- "$(dirname $0)" && pwd -P`/init.sh

table=$1
shards=$2
replicas=$3
acks=$4

splits=`gen_splits $shards`
{
    admin <<EOF
create database ${table}_db
create table $table --database ${table}_db
set replicas $table $replicas
set acks $table $acks
split shard $table $splits
EOF
} >$table.log 2>$table.log
