#!/bin/bash
. `cd -P -- "$(dirname $0)" && pwd -P`/init.sh

num=$1
# Defaults to ~1.161 to give 80-20 rule.
alpha=${2-"l(5)/l(4)"}

{
    for i in `seq $num`; do
        [[ $i -eq $num ]] && a1=1 || \
            a1="(1-e(l(1-($i/$num))*(1-(1/($alpha)))))"
        a2="(1-e(l(1-(($i-1)/$num))*(1-(1/($alpha)))))"
        calc "$a1-$a2" &
    done
    wait
} | sort -n

