#!/bin/bash
. `cd -P -- "$(dirname $0)" && pwd -P`/init.sh
mkdir -p stats

host=$1
offset=$2

while true; do
    curl "$host:$((WEB_PORT + offset))/ajax/stat?timeout=5000" \
        >stats/`date +%s.%N` 2>>statscurl.2.log || true
    sleep 1
done
