#!/bin/bash
. `cd -P -- "$(dirname $0)" && pwd -P`/init.sh

host=$1
control_file=$host.control

ssh_flags=""
ssh_flags+=" -o StrictHostKeyChecking=no"
ssh_flags+=" -o UserKnownHostsFile=/dev/null"
ssh_flags+=" -o ConnectTimeout=10"
ssh_flags+=" -i $BENCH_KEY"

control_flags=" -S $control_file"
[ -e $control_file ] && ssh_flags+=$control_flags
[ -z ${2-} ] && ssh_flags+=" -T"
echo $ssh_flags

ssh $ssh_flags ubuntu@$host

if [[ ! -e $control_file ]]; then
    echo "Establishing $control_file..." >&2
    set -m # Enable job control, because FML.
    nohup ssh -nNM $control_flags $ssh_flags ubuntu@$host >/dev/null 2>/dev/null &
fi

