// Copyright 2010-2012 RethinkDB, all rights reserved.
#include "utils.hpp"
#include "clustering/administration/main/names.hpp"

const char* names[] = {
    "Akasha",
    "Alchemist",
    "Azwraith",
    "Bane",
    "Batrider",
    "Beastmaster",
    "Bradwarden",
    "Brewmaster",
    "Bristleback",
    "Chaosknight",
    "Chen",
    "Clinkz",
    "Clockwerk",
    "Courier",
    "Dazzle",
    "Dragonknight",
    "Dragonus",
    "Drow",
    "Earthshaker",
    "Enchantress",
    "Enigma",
    "Ezalor",
    "Furion",
    "Gondar",
    "Gyrocopter",
    "Huskar",
    "Invoker",
    "Jakiro",
    "Juggernaut",
    "Kaldr",
    "Krobelus",
    "Kunkka",
    "Lanaya",
    "LeDirge",
    "Leshrac",
    "Lina",
    "Lion",
    "Luna",
    "Lycanthrope",
    "Magnus",
    "Medusa",
    "Meepo",
    "Mirana",
    "Morphling",
    "Mortred",
    "Naix",
    "Nevermore",
    "NyxNyxNyx",
    "Ogre",
    "Omniknight",
    "Ostarion",
    "Outworld",
    "Phoenix",
    "Puck",
    "Pudge",
    "Pugna",
    "Razor",
    "Rhasta",
    "Rikimaru",
    "Roshan",
    "Rubick",
    "Rylai",
    "Sandking",
    "Silencer",
    "Slardar",
    "Slark",
    "Slithice",
    "Spectre",
    "Stormspirit",
    "Strygwyr",
    "Sven",
    "Sylla",
    "Tidehunter",
    "Tinker",
    "Tiny",
    "Treant",
    "Tusk",
    "Ursa",
    "Viper",
    "Visage",
    "Weaver",
    "Windrunner",
    "Wisp",
    "Worldsmith"
};

std::string get_random_machine_name() {
    int index = randint(sizeof(names) / sizeof(char *));
    return std::string(names[index]);
}
