#!/bin/bash

# HDD I/O bound performance

if [ $DATABASE == "rethinkdb" ]; then
    ./dbench                                                                 \
        -d "$BENCH_DIR/bench_output/HDD_RAID_performance_256MB_cache" -H $SERVER_HOSTS     \
        {server}rethinkdb:"--active-data-extents 1 -c 12 -m 256 $HDD_DRIVES"                          \
        {client}stress[$STRESS_CLIENT]:"-c $CANONICAL_CLIENTS -d $CANONICAL_DURATION"          \
        iostat:1 vmstat:1 rdbstat:1
elif [ $DATABASE == "mysql" ]; then
    ./dbench                                                                 \
        -d "$BENCH_DIR/bench_output/HDD_RAID_performance_256MB_cache" -H $SERVER_HOSTS     \
        {server}mysql:"$MYSQL_HDD_COMMON_FLAGS $MYSQL_HDD_FLAGS --innodb_buffer_pool_size=256m $MYSQL_DURABILITY_FLAGS"  \
        {client}mysqlstress[$STRESS_CLIENT]:"-c $CANONICAL_CLIENTS -d $CANONICAL_DURATION"     \
        iostat:1 vmstat:1
elif [ $DATABASE == "membase" ]; then
    ./dbench                                                                                   \
        -d "$BENCH_DIR/bench_output/HDD_RAID_performance_256MB_cache" -H $SERVER_HOSTS -p 11211 \
        {server}membase:"-d /tmp/raid_mount/membase_data -m 256"                                  \
        {client}stress[$STRESS_CLIENT]:"-c $CANONICAL_CLIENTS -d $CANONICAL_DURATION" \
        iostat:1 vmstat:1
else
    echo "No workload configuration for $DATABASE"
fi
