#!/bin/bash

# $1 - password
# $2 - device
# $3 - partition info file
# $4 - mount dir
# $5 - partitioned device
# $6 - path to file
# $7 - size of file in KB

# Echo the commands
set -v

### Unmount the fs (might fail, that's ok) ###
echo $1 | sudo -S umount $4

### Do the ATA erase operation ###
echo $1 | sudo -S hdparm --user-master u --security-set-pass test $2
echo $1 | sudo -S hdparm --user-master u --security-erase test $2

### Partition the drive ###
echo $1 | sudo -S sfdisk $2 < $3

### Setup the FS ###
# Create the filesystem
echo $1 | sudo -S mke2fs -t ext2 -q -F $5

# Mount the filesystem
echo $1 | sudo -S mount -t ext2 $5 $4

### Fill the appropriate file ###
# Remove the file in case it already exists
echo $1 | sudo -S rm -f $6

# Create the file
echo $1 | sudo -S dd if=/dev/zero of=$6 bs=1024 count=$7

### Prime the drive ###
echo $1 | sudo -S rebench -d 100% -b 131072 $2

