(function(){
function d(a){throw a;}var i=void 0,k=!0,l=null,m=!1;function aa(){return function(a){return a}}var n,ba="undefined"===typeof global?window:global;ba.Bb||(ba.Bb={});var p=ba.Bb;p.global=ba;p.Sa=k;p.de="en";p.hg=function(a){p.xb(a)};p.qg=function(a){p.Sa||(a=a||"",d(Error("Importing test-only code into non-debug environment"+a?": "+a:".")))};
p.xb=function(a,b,c){a=a.split(".");c=c||p.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)!a.length&&p.ra(b)?c[e]=b:c=c[e]?c[e]:c[e]={}};p.Ff=function(a,b){for(var c=a.split("."),e=b||p.global,f;f=c.shift();)if(p.Bc(e[f]))e=e[f];else return l;return e};p.Jf=function(a,b){var c=b||p.global,e;for(e in a)c[e]=a[e]};p.Qe=function(){};p.Fd=k;p.mg=function(){};p.af="";p.bg=function(){};p.Lf=aa();p.Pe=function(){d(Error("unimplemented abstract method"))};
p.Re=function(a){a.Cf=function(){if(a.Gb)return a.Gb;p.Sa&&(p.Hb[p.Hb.length]=a);return a.Gb=new a}};p.Hb=[];
p.Q=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};p.ra=function(a){return a!==i};p.Sf=function(a){return a===l};p.Bc=function(a){return a!=l};p.isArray=function(a){return"array"==p.Q(a)};p.Ia=function(a){var b=p.Q(a);return"array"==b||"object"==b&&"number"==typeof a.length};p.Qf=function(a){return p.Ka(a)&&"function"==typeof a.getFullYear};p.v=function(a){return"string"==typeof a};p.Ib=function(a){return"boolean"==typeof a};p.Jb=function(a){return"number"==typeof a};
p.Cc=function(a){return"function"==p.Q(a)};p.Ka=function(a){var b=typeof a;return"object"==b&&a!=l||"function"==b};p.Ab=function(a){return a[p.za]||(a[p.za]=++p.ed)};p.Tc=function(a){"removeAttribute"in a&&a.removeAttribute(p.za);try{delete a[p.za]}catch(b){}};p.za="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36);p.ed=0;p.Bf=p.Ab;p.kg=p.Tc;p.ic=function(a){var b=p.Q(a);if("object"==b||"array"==b){if(a.W)return a.W();var b="array"==b?[]:{},c;for(c in a)b[c]=p.ic(a[c]);return b}return a};
p.gc=function(a,b,c){return a.call.apply(a.bind,arguments)};p.fc=function(a,b,c){a||d(Error());if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};p.bind=function(a,b,c){p.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?p.gc:p.fc;return p.bind.apply(l,arguments)};
p.Oc=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};p.Zf=function(a,b){for(var c in b)a[c]=b[c]};p.now=Date.now||function(){return+new Date};
p.If=function(a){if(p.global.execScript)p.global.execScript(a,"JavaScript");else if(p.global.eval)if(p.Da==l&&(p.global.eval("var _et_ = 1;"),"undefined"!=typeof p.global._et_?(delete p.global._et_,p.Da=k):p.Da=m),p.Da)p.global.eval(a);else{var b=p.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=m;c.appendChild(b.createTextNode(a));b.body.appendChild(c);b.body.removeChild(c)}else d(Error("goog.globalEval not available"))};p.Da=l;
p.Af=function(a,b){function c(a){for(var a=a.split("-"),b=[],c=0;c<a.length;c++)b.push(e(a[c]));return b.join("-")}function e(a){return p.ub[a]||a}var f;f=p.ub?"BY_WHOLE"==p.lc?e:c:aa();return b?a+"-"+f(b):f(a)};p.og=function(a,b){p.ub=a;p.lc=b};p.Ef=function(a,b){var c=b||{},e;for(e in c)var f=(""+c[e]).replace(/\$/g,"$$$$"),a=a.replace(RegExp("\\{\\$"+e+"\\}","gi"),f);return a};p.q=function(a,b){p.xb(a,b,i)};p.f=function(a,b,c){a[b]=c};
p.e=function(a,b){function c(){}c.prototype=b.prototype;a.Pa=b.prototype;a.prototype=new c;a.prototype.constructor=a};p.$e=function(a,b,c){var e=arguments.callee.caller;if(e.Pa)return e.Pa.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),g=m,h=a.constructor;h;h=h.Pa&&h.Pa.constructor)if(h.prototype[b]===e)g=k;else if(g)return h.prototype[b].apply(a,f);if(a[b]===e)return a.constructor.prototype[b].apply(a,f);d(Error("goog.base called from a method of one name to a method of a different name"))};
p.scope=function(a){a.call(p.global)};p.global.rethinkdb=function(a){return ca(a)};function q(a){return a instanceof r?a:t(a)}function v(a){return a instanceof da?a:ea(a)}function w(a,b){if(a){var c=b;p.isArray(b)||(c=[c]);c.some(function(b){return"string"===typeof b?typeof a===b:a instanceof b})||(p.isArray(b)&&d(new TypeError("Function argument "+a+" must be one of the types "+b)),d(new TypeError("Function argument "+a+" must be of the type "+b)))}}
function x(a,b){a.length<b&&d(new TypeError("Function requires at least "+b+" argument"+(1<b?"s.":".")))}function y(a){function b(a){return z.prototype.Ga.call(b,a)}var c=arguments[0],e=Array.prototype.slice.call(arguments,1);b.__proto__=c.prototype;c.apply(b,e);return b};function t(a){return a instanceof z?a:a===l||p.Jb(a)?y(fa,a):p.Ib(a)?y(ga,a):p.v(a)?y(ha,a):p.isArray(a)?y(ia,a):p.Ka(a)?y(ja,a):y(ka,a)}p.q("rethinkdb.expr",t);p.q("rethinkdb.js",function(a){x(arguments,1);w(a,"string");return y(la,a)});p.q("rethinkdb.table",function(a,b){x(arguments,1);w(a,"string");w(b,"boolean");return y(A,a,l,b)});p.q("rethinkdb.union",function(a){x(arguments,2);var b=q(arguments[0]);return z.prototype.Sb.apply(b,Array.prototype.slice.call(arguments,1))});function r(){}
r.prototype.ma=function(a,b){var c=b||ma;c||d(new C("No connection specified and no last connection to default to."));return c.ma(this,a)};p.f(r.prototype,"run",r.prototype.ma);r.prototype.Uc=function(a){(a?a.ma(this):this.ma(i)).Ua(function(a){1===a.length&&(a=a[0]);console.log(a)})};p.f(r.prototype,"runp",r.prototype.Uc);r.prototype.a=function(){return"----"};function na(){}p.e(na,r);na.prototype.B=function(a){var b=new oa,a=this.compile(a);b.Oa(a);a=new D;a.g(pa);E(a,3,b);return a};p.debug={};function qa(a){Error.captureStackTrace?Error.captureStackTrace(this,qa):this.stack=Error().stack||"";a&&(this.message=String(a))}p.e(qa,Error);qa.prototype.name="CustomError";p.c={};p.c.ug=function(a,b){return 0==a.lastIndexOf(b,0)};p.c.rf=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};p.c.jf=function(a,b){return 0==p.c.qb(b,a.substr(0,b.length))};p.c.hf=function(a,b){return 0==p.c.qb(b,a.substr(a.length-b.length,b.length))};p.c.Xc=function(a,b){for(var c=1;c<arguments.length;c++)var e=String(arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,e);return a};p.c.lf=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};p.c.Ja=function(a){return/^[\s\xa0]*$/.test(a)};
p.c.Rf=function(a){return p.c.Ja(p.c.Fc(a))};p.c.Pf=function(a){return!/[^\t\n\r ]/.test(a)};p.c.Nf=function(a){return!/[^a-zA-Z]/.test(a)};p.c.$a=function(a){return!/[^0-9]/.test(a)};p.c.Of=function(a){return!/[^a-zA-Z0-9]/.test(a)};p.c.Vf=function(a){return" "==a};p.c.Wf=function(a){return 1==a.length&&" "<=a&&"~">=a||"\u0080"<=a&&"\ufffd">=a};p.c.vg=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")};p.c.gf=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")};
p.c.ag=function(a){return a.replace(/\xa0|\s/g," ")};p.c.$f=function(a){return a.replace(/\xa0|[ \t]+/g," ")};p.c.kf=function(a){return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};p.c.trim=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};p.c.trimLeft=function(a){return a.replace(/^[\s\xa0]+/,"")};p.c.trimRight=function(a){return a.replace(/[\s\xa0]+$/,"")};p.c.qb=function(a,b){var c=String(a).toLowerCase(),e=String(b).toLowerCase();return c<e?-1:c==e?0:1};
p.c.Lb=/(\.\d+)|(\d+)|(\D+)/g;p.c.cg=function(a,b){if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var c=a.toLowerCase().match(p.c.Lb),e=b.toLowerCase().match(p.c.Lb),f=Math.min(c.length,e.length),g=0;g<f;g++){var h=c[g],j=e[g];if(h!=j)return c=parseInt(h,10),!isNaN(c)&&(e=parseInt(j,10),!isNaN(e)&&c-e)?c-e:h<j?-1:1}return c.length!=e.length?c.length-e.length:a<b?-1:1};p.c.Eg=function(a){return encodeURIComponent(String(a))};p.c.Dg=function(a){return decodeURIComponent(a.replace(/\+/g," "))};
p.c.Ic=function(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")};p.c.Db=function(a){if(!p.c.ac.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(p.c.cc,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(p.c.Ec,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(p.c.zc,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(p.c.Rc,"&quot;"));return a};p.c.cc=/&/g;p.c.Ec=/</g;p.c.zc=/>/g;p.c.Rc=/\"/g;p.c.ac=/[&<>\"]/;p.c.Rb=function(a){return p.c.contains(a,"&")?"document"in p.global?p.c.fd(a):p.c.gd(a):a};
p.c.fd=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(p.c.Zb,function(a,f){var g=b[a];if(g)return g;if("#"==f.charAt(0)){var h=Number("0"+f.substr(1));isNaN(h)||(g=String.fromCharCode(h))}g||(c.innerHTML=a+" ",g=c.firstChild.nodeValue.slice(0,-1));return b[a]=g})};
p.c.gd=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var e=Number("0"+c.substr(1));if(!isNaN(e))return String.fromCharCode(e)}return a}})};p.c.Zb=/&([^;\s<&]+);?/g;p.c.Fg=function(a,b){return p.c.Ic(a.replace(/  /g," &#160;"),b)};
p.c.wg=function(a,b){for(var c=b.length,e=0;e<c;e++){var f=1==c?b:b.charAt(e);if(a.charAt(0)==f&&a.charAt(a.length-1)==f)return a.substring(1,a.length-1)}return a};p.c.truncate=function(a,b,c){c&&(a=p.c.Rb(a));a.length>b&&(a=a.substring(0,b-3)+"...");c&&(a=p.c.Db(a));return a};
p.c.Cg=function(a,b,c,e){c&&(a=p.c.Rb(a));if(e&&a.length>b)e>b&&(e=b),a=a.substring(0,b-e)+"..."+a.substring(a.length-e);else if(a.length>b)var e=Math.floor(b/2),f=a.length-e,a=a.substring(0,e+b%2)+"..."+a.substring(f);c&&(a=p.c.Db(a));return a};p.c.ib={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"};p.c.La={"'":"\\'"};
p.c.quote=function(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var e=a.charAt(c),f=e.charCodeAt(0);b[c+1]=p.c.ib[e]||(31<f&&127>f?e:p.c.wb(e))}b.push('"');return b.join("")};p.c.sf=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=p.c.wb(a.charAt(c));return b.join("")};
p.c.wb=function(a){if(a in p.c.La)return p.c.La[a];if(a in p.c.ib)return p.c.La[a]=p.c.ib[a];var b=a,c=a.charCodeAt(0);if(31<c&&127>c)b=a;else{if(256>c){if(b="\\x",16>c||256<c)b+="0"}else b="\\u",4096>c&&(b+="0");b+=c.toString(16).toUpperCase()}return p.c.La[a]=b};p.c.yg=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=k;return b};p.c.contains=function(a,b){return-1!=a.indexOf(b)};p.c.tb=function(a,b){return a&&b?a.split(b).length-1:0};
p.c.Na=function(a,b,c){var e=a;0<=b&&(b<a.length&&0<c)&&(e=a.substr(0,b)+a.substr(b+c,a.length-b-c));return e};p.c.remove=function(a,b){var c=RegExp(p.c.fb(b),"");return a.replace(c,"")};p.c.ig=function(a,b){var c=RegExp(p.c.fb(b),"g");return a.replace(c,"")};p.c.fb=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};p.c.repeat=function(a,b){return Array(b+1).join(a)};
p.c.dg=function(a,b,c){a=p.ra(c)?a.toFixed(c):String(a);c=a.indexOf(".");-1==c&&(c=a.length);return p.c.repeat("0",Math.max(0,b-c))+a};p.c.Fc=function(a){return a==l?"":String(a)};p.c.ff=function(a){return Array.prototype.join.call(arguments,"")};p.c.Gf=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^p.now()).toString(36)};
p.c.nf=function(a,b){for(var c=0,e=p.c.trim(String(a)).split("."),f=p.c.trim(String(b)).split("."),g=Math.max(e.length,f.length),h=0;0==c&&h<g;h++){var j=e[h]||"",u=f[h]||"",s=RegExp("(\\d*)(\\D*)","g"),B=RegExp("(\\d*)(\\D*)","g");do{var M=s.exec(j)||["","",""],Ia=B.exec(u)||["","",""];if(0==M[0].length&&0==Ia[0].length)break;c=p.c.Va(0==M[1].length?0:parseInt(M[1],10),0==Ia[1].length?0:parseInt(Ia[1],10))||p.c.Va(0==M[2].length,0==Ia[2].length)||p.c.Va(M[2],Ia[2])}while(0==c)}return c};
p.c.Va=function(a,b){return a<b?-1:a>b?1:0};p.c.Yb=4294967296;p.c.Kf=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=p.c.Yb;return b};p.c.hd=2147483648*Math.random()|0;p.c.pf=function(){return"goog_"+p.c.hd++};p.c.ya=function(a){var b=Number(a);return 0==b&&p.c.Ja(a)?NaN:b};p.c.xg=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};p.c.zg=function(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()};
p.c.Ag=function(a,b){var c=p.v(b)?p.c.fb(b):"\\s";return a.replace(RegExp("(^"+(c?"|["+c+"]+":"")+")([a-z])","g"),function(a,b,c){return b+c.toUpperCase()})};p.c.eg=function(a){isFinite(a)&&(a=String(a));return p.v(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};p.p={};p.p.U=p.Sa;function ra(a,b){b.unshift(a);qa.call(this,p.c.Xc.apply(l,b));b.shift();this.Yf=a}p.e(ra,qa);ra.prototype.name="AssertionError";p.p.X=function(a,b,c,e){var f="Assertion failed";if(c)var f=f+(": "+c),g=e;else a&&(f+=": "+a,g=b);d(new ra(""+f,g||[]))};p.p.assert=function(a,b,c){p.p.U&&!a&&p.p.X("",l,b,Array.prototype.slice.call(arguments,2));return a};p.p.tf=function(a,b){p.p.U&&d(new ra("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};
p.p.Xe=function(a,b,c){p.p.U&&!p.Jb(a)&&p.p.X("Expected number but got %s: %s.",[p.Q(a),a],b,Array.prototype.slice.call(arguments,2));return a};p.p.Ze=function(a,b,c){p.p.U&&!p.v(a)&&p.p.X("Expected string but got %s: %s.",[p.Q(a),a],b,Array.prototype.slice.call(arguments,2));return a};p.p.Ve=function(a,b,c){p.p.U&&!p.Cc(a)&&p.p.X("Expected function but got %s: %s.",[p.Q(a),a],b,Array.prototype.slice.call(arguments,2));return a};
p.p.Ye=function(a,b,c){p.p.U&&!p.Ka(a)&&p.p.X("Expected object but got %s: %s.",[p.Q(a),a],b,Array.prototype.slice.call(arguments,2));return a};p.p.Te=function(a,b,c){p.p.U&&!p.isArray(a)&&p.p.X("Expected array but got %s: %s.",[p.Q(a),a],b,Array.prototype.slice.call(arguments,2));return a};p.p.Ue=function(a,b,c){p.p.U&&!p.Ib(a)&&p.p.X("Expected boolean but got %s: %s.",[p.Q(a),a],b,Array.prototype.slice.call(arguments,2));return a};
p.p.We=function(a,b,c,e){p.p.U&&!(a instanceof b)&&p.p.X("instanceof check failed.",l,c,Array.prototype.slice.call(arguments,3));return a};p.h={};p.h.i={};p.h.i.$b=m;p.h.i.assert=function(){};p.h.i.rb=function(){return p.h.i.$b};function sa(a,b,c){this.Nc=a;p.h.i.assert(p.c.$a(b));this.G=b;this.L=c.name;this.$=!!c.R;this.Tf=!!c.required;this.K=c.b;this.cb=c.type;this.oc=m;switch(this.K){case ta:case ua:case va:case wa:case xa:this.oc=k}this.Ya=c.defaultValue}var ta=3,ua=4,va=6,wa=16,xa=18;sa.prototype.Z=function(){return this.Nc.A};function ya(a){return 11==a.K||10==a.K}function za(a){return a.$};p.object={};p.object.forEach=function(a,b,c){for(var e in a)b.call(c,a[e],e,a)};p.object.filter=function(a,b,c){var e={},f;for(f in a)b.call(c,a[f],f,a)&&(e[f]=a[f]);return e};p.object.map=function(a,b,c){var e={},f;for(f in a)e[f]=b.call(c,a[f],f,a);return e};p.object.some=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return k;return m};p.object.every=function(a,b,c){for(var e in a)if(!b.call(c,a[e],e,a))return m;return k};p.object.zf=function(a){var b=0,c;for(c in a)b++;return b};
p.object.xf=function(a){for(var b in a)return b};p.object.yf=function(a){for(var b in a)return a[b]};p.object.contains=function(a,b){return p.object.jc(a,b)};p.object.xc=function(a){var b=[],c=0,e;for(e in a)b[c++]=a[e];return b};p.object.Df=function(a){var b=[],c=0,e;for(e in a)b[c++]=e;return b};p.object.Hf=function(a,b){for(var c=p.Ia(b),e=c?b:arguments,c=c?0:1;c<e.length&&!(a=a[e[c]],!p.ra(a));c++);return a};p.object.of=function(a,b){return b in a};
p.object.jc=function(a,b){for(var c in a)if(a[c]==b)return k;return m};p.object.tc=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return e};p.object.vf=function(a,b,c){return(b=p.object.tc(a,b,c))&&a[b]};p.object.Ja=function(a){for(var b in a)return m;return k};p.object.clear=function(a){for(var b in a)delete a[b]};p.object.remove=function(a,b){var c;(c=b in a)&&delete a[b];return c};
p.object.add=function(a,b,c){b in a&&d(Error('The object already contains the key "'+b+'"'));p.object.set(a,b,c)};p.object.get=function(a,b,c){return b in a?a[b]:c};p.object.set=function(a,b,c){a[b]=c};p.object.pg=function(a,b,c){return b in a?a[b]:a[b]=c};p.object.W=function(a){var b={},c;for(c in a)b[c]=a[c];return b};p.object.jd=function(a){var b=p.Q(a);if("object"==b||"array"==b){if(a.W)return a.W();var b="array"==b?[]:{},c;for(c in a)b[c]=p.object.jd(a[c]);return b}return a};
p.object.Bg=function(a){var b={},c;for(c in a)b[a[c]]=c;return b};p.object.kb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");p.object.extend=function(a,b){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)a[c]=e[c];for(var g=0;g<p.object.kb.length;g++)c=p.object.kb[g],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};
p.object.create=function(a){var b=arguments.length;if(1==b&&p.isArray(arguments[0]))return p.object.create.apply(l,arguments[0]);b%2&&d(Error("Uneven number of arguments"));for(var c={},e=0;e<b;e+=2)c[arguments[e]]=arguments[e+1];return c};p.object.kc=function(a){var b=arguments.length;if(1==b&&p.isArray(arguments[0]))return p.object.kc.apply(l,arguments[0]);for(var c={},e=0;e<b;e++)c[arguments[e]]=k;return c};p.d={};p.ba=k;p.d.fg=function(a){return a[a.length-1]};p.d.t=Array.prototype;p.d.indexOf=p.ba&&p.d.t.indexOf?function(a,b,c){return p.d.t.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(p.v(a))return!p.v(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
p.d.lastIndexOf=p.ba&&p.d.t.lastIndexOf?function(a,b,c){return p.d.t.lastIndexOf.call(a,b,c==l?a.length-1:c)}:function(a,b,c){c=c==l?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(p.v(a))return!p.v(b)||1!=b.length?-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};p.d.forEach=p.ba&&p.d.t.forEach?function(a,b,c){p.d.t.forEach.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=p.v(a)?a.split(""):a,g=0;g<e;g++)g in f&&b.call(c,f[g],g,a)};
p.d.vc=function(a,b){for(var c=p.v(a)?a.split(""):a,e=a.length-1;0<=e;--e)e in c&&b.call(i,c[e],e,a)};p.d.filter=p.ba&&p.d.t.filter?function(a,b,c){return p.d.t.filter.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=[],g=0,h=p.v(a)?a.split(""):a,j=0;j<e;j++)if(j in h){var u=h[j];b.call(c,u,j,a)&&(f[g++]=u)}return f};
p.d.map=p.ba&&p.d.t.map?function(a,b,c){return p.d.t.map.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=Array(e),g=p.v(a)?a.split(""):a,h=0;h<e;h++)h in g&&(f[h]=b.call(c,g[h],h,a));return f};p.d.reduce=function(a,b,c,e){if(a.reduce)return e?a.reduce(p.bind(b,e),c):a.reduce(b,c);var f=c;p.d.forEach(a,function(c,h){f=b.call(e,f,c,h,a)});return f};
p.d.reduceRight=function(a,b,c,e){if(a.reduceRight)return e?a.reduceRight(p.bind(b,e),c):a.reduceRight(b,c);var f=c;p.d.vc(a,function(c,h){f=b.call(e,f,c,h,a)});return f};p.d.some=p.ba&&p.d.t.some?function(a,b,c){return p.d.t.some.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=p.v(a)?a.split(""):a,g=0;g<e;g++)if(g in f&&b.call(c,f[g],g,a))return k;return m};
p.d.every=p.ba&&p.d.t.every?function(a,b,c){return p.d.t.every.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=p.v(a)?a.split(""):a,g=0;g<e;g++)if(g in f&&!b.call(c,f[g],g,a))return m;return k};p.d.find=function(a,b,c){b=p.d.yb(a,b,c);return 0>b?l:p.v(a)?a.charAt(b):a[b]};p.d.yb=function(a,b,c){for(var e=a.length,f=p.v(a)?a.split(""):a,g=0;g<e;g++)if(g in f&&b.call(c,f[g],g,a))return g;return-1};p.d.uf=function(a,b,c){b=p.d.sc(a,b,c);return 0>b?l:p.v(a)?a.charAt(b):a[b]};
p.d.sc=function(a,b,c){for(var e=p.v(a)?a.split(""):a,f=a.length-1;0<=f;f--)if(f in e&&b.call(c,e[f],f,a))return f;return-1};p.d.contains=function(a,b){return 0<=p.d.indexOf(a,b)};p.d.Ja=function(a){return 0==a.length};p.d.clear=function(a){if(!p.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};p.d.Eb=function(a,b){p.d.contains(a,b)||a.push(b)};p.d.Fb=function(a,b,c){p.d.splice(a,c,0,b)};p.d.Mf=function(a,b,c){p.Oc(p.d.splice,a,c,0).apply(l,b)};
p.d.insertBefore=function(a,b,c){var e;2==arguments.length||0>(e=p.d.indexOf(a,c))?a.push(b):p.d.Fb(a,b,e)};p.d.remove=function(a,b){var c=p.d.indexOf(a,b),e;(e=0<=c)&&p.d.Na(a,c);return e};p.d.Na=function(a,b){return 1==p.d.t.splice.call(a,b,1).length};p.d.lg=function(a,b,c){b=p.d.yb(a,b,c);return 0<=b?(p.d.Na(a,b),k):m};p.d.concat=function(a){return p.d.t.concat.apply(p.d.t,arguments)};p.d.cd=function(a){var b=a.length;if(0<b){for(var c=Array(b),e=0;e<b;e++)c[e]=a[e];return c}return[]};p.d.W=p.d.cd;
p.d.extend=function(a,b){for(var c=1;c<arguments.length;c++){var e=arguments[c],f;if(p.isArray(e)||(f=p.Ia(e))&&e.hasOwnProperty("callee"))a.push.apply(a,e);else if(f)for(var g=a.length,h=e.length,j=0;j<h;j++)a[g+j]=e[j];else a.push(e)}};p.d.splice=function(a,b,c,e){return p.d.t.splice.apply(a,p.d.slice(arguments,1))};p.d.slice=function(a,b,c){return 2>=arguments.length?p.d.t.slice.call(a,b):p.d.t.slice.call(a,b,c)};
p.d.jg=function(a,b){for(var c=b||a,e={},f=0,g=0;g<a.length;){var h=a[g++],j=p.Ka(h)?"o"+p.Ab(h):(typeof h).charAt(0)+h;Object.prototype.hasOwnProperty.call(e,j)||(e[j]=k,c[f++]=h)}c.length=f};p.d.ob=function(a,b,c){return p.d.pb(a,c||p.d.da,m,b)};p.d.df=function(a,b,c){return p.d.pb(a,b,k,i,c)};p.d.pb=function(a,b,c,e,f){for(var g=0,h=a.length,j;g<h;){var u=g+h>>1,s;s=c?b.call(f,a[u],u,a):b(e,a[u]);0<s?g=u+1:(h=u,j=!s)}return j?g:~g};p.d.sort=function(a,b){p.d.t.sort.call(a,b||p.d.da)};
p.d.tg=function(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var e=b||p.d.da;p.d.sort(a,function(a,b){return e(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value};p.d.sg=function(a,b,c){var e=c||p.d.da;p.d.sort(a,function(a,c){return e(a[b],c[b])})};p.d.Uf=function(a,b,c){for(var b=b||p.d.da,e=1;e<a.length;e++){var f=b(a[e-1],a[e]);if(0<f||0==f&&c)return m}return k};
p.d.z=function(a,b,c){if(!p.Ia(a)||!p.Ia(b)||a.length!=b.length)return m;for(var e=a.length,c=c||p.d.mc,f=0;f<e;f++)if(!c(a[f],b[f]))return m;return k};p.d.ha=function(a,b,c){return p.d.z(a,b,c)};p.d.mf=function(a,b,c){for(var c=c||p.d.da,e=Math.min(a.length,b.length),f=0;f<e;f++){var g=c(a[f],b[f]);if(0!=g)return g}return p.d.da(a.length,b.length)};p.d.da=function(a,b){return a>b?1:a<b?-1:0};p.d.mc=function(a,b){return a===b};
p.d.bf=function(a,b,c){c=p.d.ob(a,b,c);return 0>c?(p.d.Fb(a,b,-(c+1)),k):m};p.d.cf=function(a,b,c){b=p.d.ob(a,b,c);return 0<=b?p.d.Na(a,b):m};p.d.ef=function(a,b){for(var c={},e=0;e<a.length;e++){var f=a[e],g=b(f,e,a);p.ra(g)&&(c[g]||(c[g]=[])).push(f)}return c};p.d.repeat=function(a,b){for(var c=[],e=0;e<b;e++)c[e]=a;return c};p.d.uc=function(a){for(var b=[],c=0;c<arguments.length;c++){var e=arguments[c];p.isArray(e)?b.push.apply(b,p.d.uc.apply(l,e)):b.push(e)}return b};
p.d.rotate=function(a,b){a.length&&(b%=a.length,0<b?p.d.t.unshift.apply(a,a.splice(-b,b)):0>b&&p.d.t.push.apply(a,a.splice(0,-b)));return a};p.d.Vb=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var e=[],f=0;f<arguments.length;f++){var g=arguments[f];if(c>=g.length)return b;e.push(g[c])}b.push(e)}};p.d.rg=function(a,b){for(var c=b||Math.random,e=a.length-1;0<e;e--){var f=Math.floor(c()*(e+1)),g=a[e];a[e]=a[f];a[f]=g}};function Aa(a,b,c){this.Gc=a;this.L=b.name||l;this.wf=b.k||l;this.sb=b.u;this.Y={};for(a=0;a<c.length;a++)b=c[a],this.Y[b.G]=b}Aa.prototype.Z=function(){return!this.sb?l:this.sb.ja()};function Ba(a){a=p.object.xc(a.Y);p.d.sort(a,function(a,c){return a.G-c.G});return a};function F(){this.H={};this.A=this.constructor.A;this.Y=this.A.Y;this.C=this.Kb=l}n=F.prototype;n.ja=function(){return this.A};function Ca(a,b){p.h.i.assert(b.Z()==a.A,"The current message does not contain the given field");return Da(a,b.G)}n.tb=function(a){p.h.i.assert(a.Z()==this.A,"The current message does not contain the given field");a=a.G;za(Ea(this,a))?(Da(this,a)&&p.h.i.assert(p.isArray(this.H[a])),a=Da(this,a)?this.H[a].length:0):a=Da(this,a)?1:0;return a};
n.get=function(a,b){p.h.i.assert(a.Z()==this.A,"The current message does not contain the given field");return G(this,a.G,b)};n.set=function(a,b){p.h.i.assert(a.Z()==this.A,"The current message does not contain the given field");E(this,a.G,b)};n.add=function(a,b){p.h.i.assert(a.Z()==this.A,"The current message does not contain the given field");H(this,a.G,b)};
n.clear=function(a){p.h.i.assert(a.Z()==this.A,"The current message does not contain the given field");a=a.G;p.h.i.assert(Ea(this,a),"Unknown field");delete this.H[a];this.C&&delete this.C[a]};
n.z=function(a){if(!a||this.constructor!=a.constructor)return m;for(var b=Ba(this.ja()),c=0;c<b.length;c++){var e=b[c];if(Ca(this,e)!=Ca(a,e))return m;if(Ca(this,e)){var f=ya(e),g=Fa(this,e),h=Fa(a,e);if(e.$){if(g.length!=h.length)return m;for(e=0;e<g.length;e++)if(!(f?g[e].z(h[e]):g[e]==h[e]))return m}else if(!(f?g.z(h):g==h))return m}}return k};
function Ga(a,b){p.h.i.assert(a.constructor==b.constructor,"The source message must have the same type.");for(var c=Ba(a.ja()),e=0;e<c.length;e++){var f=c[e];if(Ca(b,f)){a.C&&delete a.C[f.G];var g=ya(f);if(f.$){var h;h=b;var j=f;p.h.i.assert(j.Z()==h.A,"The current message does not contain the given field");h=Ha(h,j.G);for(j=0;j<h.length;j++)a.add(f,g?h[j].W():h[j])}else h=Fa(b,f),g?(g=Fa(a,f))?Ga(g,h):a.set(f,h.W()):a.set(f,h)}}}
n.W=function(){var a=new this.constructor;p.h.i.assert(a.constructor==this.constructor,"The source message must have the same type.");a.H={};a.C&&(a.C={});Ga(a,this);return a};function Ea(a,b){p.h.i.assert(a.Y[b],"No field found for the given tag");return a.Y[b]}function Da(a,b){p.h.i.assert(a.Y[b],"No field found for the given tag");return b in a.H&&p.ra(a.H[b])&&a.H[b]!==l}
function Fa(a,b){var c=b.G;if(!c in a.H)return l;var e=a.H[c];return e==l?l:a.Kb?!(c in a.C)?(e=a.Kb.qf(a,b,e),a.C[c]=e):a.C[c]:e}function G(a,b,c){b=Ea(a,b);a=Fa(a,b);if(b.$)return p.h.i.assert(p.isArray(a)),c=c||0,p.h.i.assert(0<=c&&c<a.length,"Given index is out of bounds"),a[c];p.h.i.assert(!p.isArray(a));return a}function Ja(a,b){var c;if(Da(a,b))c=G(a,b,i);else{c=Ea(a,b);if(c.Ya===i){var e=c.cb;c.Ya=e===Boolean?m:e===Number?0:e===String?"":new e}c=c.Ya}return c}
function Ha(a,b){p.h.i.assert(za(Ea(a,b)),"Cannot call fieldArray on a non-repeated field");var c=Ea(a,b),c=Fa(a,c);p.h.i.assert(c==l||p.isArray(c));return c||[]}function E(a,b,c){if(p.h.i.rb()){var e=Ea(a,b);p.h.i.assert(!e.$,"Cannot call set on a repeated field");Ka(e,c)}a.H[b]=c;a.C&&(a.C[b]=c)}function H(a,b,c){if(p.h.i.rb()){var e=Ea(a,b);p.h.i.assert(e.$,"Cannot call add on a non-repeated field");Ka(e,c)}a.H[b]||(a.H[b]=[]);a.H[b].push(c);a.C&&delete a.C[b]}
function Ka(a,b){p.h.i.assert(b!==l);var c=a.cb;c===String?p.h.i.assert("string"===typeof b,"Expected value of type string"):c===Boolean?p.h.i.assert("boolean"===typeof b,"Expected value of type boolean"):c===Number?p.h.i.assert("number"===typeof b,"Expected value of type number"):14==a.K?p.h.i.assert("number"===typeof b,"Expected an enum value, which is a number"):p.h.i.assert(b instanceof c,"Expected a matching message type")}
function I(a,b){var c=[],e,f;for(f in b)b.hasOwnProperty(f)&&(p.h.i.assert(p.c.$a(f),"Keys must be numeric"),0==f?e=b[0]:c.push(new sa(a,f,b[f])));p.h.i.assert(e);a.A=new Aa(a,e,c);a.ja=function(){return a.A}};function J(){F.apply(this)}p.e(J,F);J.prototype.va=function(a){E(this,1,a)};function La(){F.apply(this)}p.e(La,F);La.prototype.na=function(a){E(this,1,a)};La.prototype.Oa=function(a){E(this,2,a)};function K(){F.apply(this)}p.e(K,F);K.prototype.g=function(a){E(this,1,a)};K.prototype.na=function(a){E(this,2,a)};function Ma(a){return Ja(a,15)}function Na(){F.apply(this)}p.e(Na,F);function Oa(){F.apply(this)}p.e(Oa,F);function Pa(){F.apply(this)}p.e(Pa,F);function Qa(){F.apply(this)}p.e(Qa,F);
Qa.prototype.O=function(){return Ja(this,1)};Qa.prototype.F=function(a){E(this,1,a)};Qa.prototype.V=function(a){E(this,2,a)};Qa.prototype.fa=function(a){E(this,3,a)};function Ra(){F.apply(this)}p.e(Ra,F);Ra.prototype.O=function(){return Ja(this,1)};Ra.prototype.F=function(a){E(this,1,a)};function L(){F.apply(this)}p.e(L,F);L.prototype.g=function(a){E(this,1,a)};L.prototype.Ga=function(){return G(this,2)};L.prototype.ua=function(a){E(this,2,a)};
var Sa=19,Ta={me:1,Ld:2,Rd:3,Pd:4,Sd:5,se:6,Td:7,ge:8,qd:9,Ae:11,md:14,Ee:15,je:16,Cd:17,ie:18,vd:Sa,Id:20,fe:21,wd:22,re:23,Bd:24,$d:26,Ke:27,oe:28,Ce:29,rd:30,ye:31,Nd:32,od:35,nd:36,we:37,Vd:38,Ne:39};function Ua(){F.apply(this)}p.e(Ua,F);function Va(){F.apply(this)}p.e(Va,F);Va.prototype.P=function(a){E(this,1,a)};function Wa(){F.apply(this)}p.e(Wa,F);Wa.prototype.P=function(a){E(this,1,a)};function Xa(){F.apply(this)}p.e(Xa,F);Xa.prototype.Ga=function(){return G(this,1)};
Xa.prototype.ua=function(a){E(this,1,a)};function Ya(){F.apply(this)}p.e(Ya,F);function Za(){F.apply(this)}p.e(Za,F);Za.prototype.V=function(a){E(this,1,a)};function $a(){F.apply(this)}p.e($a,F);$a.prototype.D=function(a){E(this,4,a)};function N(){F.apply(this)}p.e(N,F);N.prototype.S=function(a){E(this,1,a)};N.prototype.D=function(a){E(this,2,a)};function ab(){F.apply(this)}p.e(ab,F);ab.prototype.S=function(a){E(this,1,a)};ab.prototype.D=function(a){E(this,2,a)};function oa(){F.apply(this)}
p.e(oa,F);oa.prototype.Oa=function(a){E(this,1,a)};function O(){F.apply(this)}p.e(O,F);O.prototype.g=function(a){E(this,1,a)};function bb(){F.apply(this)}p.e(bb,F);bb.prototype.wa=function(a){E(this,1,a)};bb.prototype.P=function(a){E(this,2,a)};function cb(){F.apply(this)}p.e(cb,F);cb.prototype.wa=function(a){E(this,1,a)};function db(){F.apply(this)}p.e(db,F);db.prototype.wa=function(a){E(this,1,a)};db.prototype.P=function(a){E(this,2,a)};function eb(){F.apply(this)}p.e(eb,F);
eb.prototype.O=function(){return Ja(this,1)};eb.prototype.F=function(a){E(this,1,a)};function fb(){F.apply(this)}p.e(fb,F);fb.prototype.na=function(a){E(this,2,a)};function gb(){F.apply(this)}p.e(gb,F);n=gb.prototype;n.O=function(){return Ja(this,1)};n.F=function(a){E(this,1,a)};n.V=function(a){E(this,2,a)};n.fa=function(a){E(this,3,a)};n.P=function(a){E(this,4,a)};function hb(){F.apply(this)}p.e(hb,F);hb.prototype.O=function(){return Ja(this,1)};hb.prototype.F=function(a){E(this,1,a)};
hb.prototype.V=function(a){E(this,2,a)};hb.prototype.fa=function(a){E(this,3,a)};function ib(){F.apply(this)}p.e(ib,F);n=ib.prototype;n.O=function(){return Ja(this,1)};n.F=function(a){E(this,1,a)};n.V=function(a){E(this,2,a)};n.fa=function(a){E(this,3,a)};n.P=function(a){E(this,4,a)};function jb(){F.apply(this)}p.e(jb,F);jb.prototype.g=function(a){E(this,1,a)};jb.prototype.va=function(a){E(this,2,a)};function kb(){F.apply(this)}p.e(kb,F);kb.prototype.O=function(){return Ja(this,3)};
kb.prototype.F=function(a){E(this,3,a)};function D(){F.apply(this)}p.e(D,F);D.prototype.g=function(a){E(this,1,a)};D.prototype.ea=function(){return G(this,2)};D.prototype.hb=function(a){E(this,2,a)};var pa=1,lb={xe:pa,Oe:2,xd:3,Be:4,he:5};function mb(){F.apply(this)}p.e(mb,F);mb.prototype.ea=function(){return G(this,2)};mb.prototype.hb=function(a){E(this,2,a)};function nb(){F.apply(this)}p.e(nb,F);
I(J,{"0":{name:"TableRef",k:"TableRef"},1:{name:"db_name",b:9,type:String},2:{name:"table_name",b:9,type:String},3:{name:"use_outdated",b:8,defaultValue:0,type:Boolean}});I(La,{"0":{name:"VarTermTuple",k:"VarTermTuple"},1:{name:"var",b:9,type:String},2:{name:"term",b:11,type:K}});
I(K,{"0":{name:"Term",k:"Term"},1:{name:"type",b:14,defaultValue:0,type:{Yd:0,Me:1,ae:2,ud:3,Qd:4,Hd:5,pe:6,De:7,JSON:8,BOOL:9,pd:10,qe:11,Md:12,Je:13,Xd:14,Ud:15}},2:{name:"var",b:9,type:String},3:{name:"let",b:11,type:Na},4:{name:"call",b:11,type:Oa},5:{name:"if_",b:11,type:Pa},6:{name:"error",b:9,type:String},7:{name:"number",b:1,type:Number},8:{name:"valuestring",b:9,type:String},9:{name:"jsonstring",b:9,type:String},10:{name:"valuebool",b:8,type:Boolean},11:{name:"array",R:k,b:11,type:K},12:{name:"object",
R:k,b:11,type:La},14:{name:"get_by_key",b:11,type:Qa},15:{name:"table",b:11,type:Ra},16:{name:"javascript",b:9,type:String}});I(Na,{"0":{name:"Let",u:K,k:"Term.Let"},1:{name:"binds",R:k,b:11,type:La},2:{name:"expr",b:11,type:K}});I(Oa,{"0":{name:"Call",u:K,k:"Term.Call"},1:{name:"builtin",b:11,type:L},2:{name:"args",R:k,b:11,type:K}});I(Pa,{"0":{name:"If",u:K,k:"Term.If"},1:{name:"test",b:11,type:K},2:{name:"true_branch",b:11,type:K},3:{name:"false_branch",b:11,type:K}});
I(Qa,{"0":{name:"GetByKey",u:K,k:"Term.GetByKey"},1:{name:"table_ref",b:11,type:J},2:{name:"attrname",b:9,type:String},3:{name:"key",b:11,type:K}});I(Ra,{"0":{name:"Table",u:K,k:"Term.Table"},1:{name:"table_ref",b:11,type:J}});
I(L,{"0":{name:"Builtin",k:"Builtin"},1:{name:"type",b:14,defaultValue:1,type:Ta},2:{name:"attr",b:9,type:String},3:{name:"attrs",R:k,b:9,type:String},4:{name:"comparison",b:14,defaultValue:1,type:{Gd:1,le:2,ee:3,Zd:4,Od:5,Kd:6}},5:{name:"filter",b:11,type:Ua},6:{name:"map",b:11,type:Va},7:{name:"concat_map",b:11,type:Wa},8:{name:"order_by",R:k,b:11,type:Xa},9:{name:"reduce",b:11,type:$a},10:{name:"grouped_map_reduce",b:11,type:Ya},11:{name:"range",b:11,type:Za}});
I(Ua,{"0":{name:"Filter",u:L,k:"Builtin.Filter"},1:{name:"predicate",b:11,type:ab}});I(Va,{"0":{name:"Map",u:L,k:"Builtin.Map"},1:{name:"mapping",b:11,type:N}});I(Wa,{"0":{name:"ConcatMap",u:L,k:"Builtin.ConcatMap"},1:{name:"mapping",b:11,type:N}});I(Xa,{"0":{name:"OrderBy",u:L,k:"Builtin.OrderBy"},1:{name:"attr",b:9,type:String},2:{name:"ascending",b:8,defaultValue:1,type:Boolean}});
I(Ya,{"0":{name:"GroupedMapReduce",u:L,k:"Builtin.GroupedMapReduce"},1:{name:"group_mapping",b:11,type:N},2:{name:"value_mapping",b:11,type:N},3:{name:"reduction",b:11,type:$a}});I(Za,{"0":{name:"Range",u:L,k:"Builtin.Range"},1:{name:"attrname",b:9,type:String},2:{name:"lowerbound",b:11,type:K},3:{name:"upperbound",b:11,type:K}});I($a,{"0":{name:"Reduction",k:"Reduction"},1:{name:"base",b:11,type:K},2:{name:"var1",b:9,type:String},3:{name:"var2",b:9,type:String},4:{name:"body",b:11,type:K}});
I(N,{"0":{name:"Mapping",k:"Mapping"},1:{name:"arg",b:9,type:String},2:{name:"body",b:11,type:K}});I(ab,{"0":{name:"Predicate",k:"Predicate"},1:{name:"arg",b:9,type:String},2:{name:"body",b:11,type:K}});I(oa,{"0":{name:"ReadQuery",k:"ReadQuery"},1:{name:"term",b:11,type:K},2:{name:"max_chunk_size",b:3,type:String},3:{name:"max_age",b:3,type:String}});
I(O,{"0":{name:"WriteQuery",k:"WriteQuery"},1:{name:"type",b:14,defaultValue:1,type:{Le:1,Ad:2,ke:3,Wd:4,Jd:6,ve:7,te:8,ue:9}},11:{name:"atomic",b:8,defaultValue:1,type:Boolean},2:{name:"update",b:11,type:bb},3:{name:"delete",b:11,type:cb},4:{name:"mutate",b:11,type:db},5:{name:"insert",b:11,type:eb},7:{name:"for_each",b:11,type:fb},8:{name:"point_update",b:11,type:gb},9:{name:"point_delete",b:11,type:hb},10:{name:"point_mutate",b:11,type:ib}});
I(bb,{"0":{name:"Update",u:O,k:"WriteQuery.Update"},1:{name:"view",b:11,type:K},2:{name:"mapping",b:11,type:N}});I(cb,{"0":{name:"Delete",u:O,k:"WriteQuery.Delete"},1:{name:"view",b:11,type:K}});I(db,{"0":{name:"Mutate",u:O,k:"WriteQuery.Mutate"},1:{name:"view",b:11,type:K},2:{name:"mapping",b:11,type:N}});I(eb,{"0":{name:"Insert",u:O,k:"WriteQuery.Insert"},1:{name:"table_ref",b:11,type:J},2:{name:"terms",R:k,b:11,type:K},3:{name:"overwrite",b:8,defaultValue:0,type:Boolean}});
I(fb,{"0":{name:"ForEach",u:O,k:"WriteQuery.ForEach"},1:{name:"stream",b:11,type:K},2:{name:"var",b:9,type:String},3:{name:"queries",R:k,b:11,type:O}});I(gb,{"0":{name:"PointUpdate",u:O,k:"WriteQuery.PointUpdate"},1:{name:"table_ref",b:11,type:J},2:{name:"attrname",b:9,type:String},3:{name:"key",b:11,type:K},4:{name:"mapping",b:11,type:N}});I(hb,{"0":{name:"PointDelete",u:O,k:"WriteQuery.PointDelete"},1:{name:"table_ref",b:11,type:J},2:{name:"attrname",b:9,type:String},3:{name:"key",b:11,type:K}});
I(ib,{"0":{name:"PointMutate",u:O,k:"WriteQuery.PointMutate"},1:{name:"table_ref",b:11,type:J},2:{name:"attrname",b:9,type:String},3:{name:"key",b:11,type:K},4:{name:"mapping",b:11,type:N}});I(jb,{"0":{name:"MetaQuery",k:"MetaQuery"},1:{name:"type",b:14,defaultValue:1,type:{yd:1,Dd:2,be:3,zd:4,Ed:5,ce:6}},2:{name:"db_name",b:9,type:String},3:{name:"create_table",b:11,type:kb},4:{name:"drop_table",b:11,type:J}});
I(kb,{"0":{name:"CreateTable",u:jb,k:"MetaQuery.CreateTable"},1:{name:"datacenter",b:9,type:String},3:{name:"table_ref",b:11,type:J},4:{name:"primary_key",b:9,defaultValue:"id",type:String},5:{name:"cache_size",b:3,defaultValue:"1073741824",type:String}});I(D,{"0":{name:"Query",k:"Query"},1:{name:"type",b:14,defaultValue:pa,type:lb},2:{name:"token",b:3,type:String},3:{name:"read_query",b:11,type:oa},4:{name:"write_query",b:11,type:O},5:{name:"meta_query",b:11,type:jb}});
I(mb,{"0":{name:"Response",k:"Response"},1:{name:"status_code",b:14,defaultValue:0,type:{Fe:0,Ge:1,He:2,Ie:3,td:101,sd:102,ze:103}},2:{name:"token",b:3,type:String},3:{name:"response",R:k,b:9,type:String},4:{name:"error_message",b:9,type:String},5:{name:"backtrace",b:11,type:nb}});I(nb,{"0":{name:"Backtrace",u:mb,k:"Response.Backtrace"},1:{name:"frame",R:k,b:9,type:String}});function z(){}p.e(z,na);function ob(a){this.Hc=a||""}p.e(ob,z);ob.prototype.compile=function(){var a=new K;a.g(5);E(a,6,this.Hc);return a};ob.prototype.a=function(a){return a?"^^^^^^^^^":"r.error()"};p.q("rethinkdb.error",function(){return new ob});function ka(a){this.o=a}p.e(ka,z);ka.prototype.compile=function(){var a=new K;a.g(8);var b=JSON.stringify(this.o);E(a,9,b);return a};function fa(a){this.o="undefined"===typeof a?l:a}p.e(fa,z);
fa.prototype.compile=function(){var a=new K;this.o===l?a.g(0):(a.g(6),E(a,7,this.o));return a};fa.prototype.a=function(a){var b="r.expr("+this.o+")";return a?P(b):b};function ga(a){this.o=a}p.e(ga,z);ga.prototype.compile=function(){var a=new K;a.g(9);E(a,10,this.o);return a};ga.prototype.a=function(a){var b="r.expr("+this.o+")";return a?P(b):b};function ha(a){this.o=a}p.e(ha,z);ha.prototype.compile=function(){var a=new K;a.g(7);E(a,8,this.o);return a};
ha.prototype.a=function(a){var b="r.expr('"+this.o+"')";return a?P(b):b};function ia(a){this.o=[];for(var b=0;b<a.length;b++){var c=q(a[b]);this.o.push(c)}}p.e(ia,z);ia.prototype.compile=function(a){var b=new K;b.g(10);for(var c=0;c<this.o.length;c++){var e=this.o[c].compile(a);H(b,11,e)}return b};
ia.prototype.a=function(a){var b=this.o.map(function(a){return a.a()});if(a){if(0===a.length)return P("r.expr(["+b.join(", ")+"])");var c=a[0].split(":");a.shift();c=parseInt(c[1],10);b=b.map(Q);b[c]=this.o[c].a(a);return"        "+b.join("  ")+"  "}return"r.expr(["+b.join(", ")+"])"};function ja(a){this.o={};for(var b in a)if(a.hasOwnProperty(b)){var c=q(a[b]);this.o[b]=c}}p.e(ja,z);
ja.prototype.compile=function(a){var b=new K;b.g(11);for(var c in this.o)if(this.o.hasOwnProperty(c)){var e=new La;e.na(c);e.Oa(this.o[c].compile(a));H(b,12,e)}return b};
ja.prototype.a=function(a){var b=[],c;for(c in this.o)this.o.hasOwnProperty(c)&&b.push("'"+c+"':"+this.o[c].a());b="r.expr({"+b.join(", ")+"})";if(a){if(0===a.length)return P(b);b=a[0].split(":");a.shift();var e=b[1],b=[];for(c in this.o)this.o.hasOwnProperty(c)&&(c===e?b.push(Q("'"+c+"':")+this.o[c].a(a)):b.push(Q("'"+c+"':"+this.o[c].a())));return"        "+b.join("  ")+"  "}return b};function la(a){this.Ob=a}p.e(la,z);la.prototype.compile=function(){var a=new K;a.g(14);E(a,16,this.Ob);return a};
la.prototype.a=function(a){var b="r.js('"+this.Ob+"')";return a?P(b):b};function da(a,b){1>a.length&&a.push("");this.w=a;this.body=b}da.prototype.a=function(a){return a?Q("function("+this.w.join(", ")+") {return ")+this.body.a(a)+" ":"function("+this.w.join(", ")+") {return "+this.body.a()+"}"};var pb=0;
function ea(a){var b,c;if("function"===typeof a&&!(a instanceof r)){b=[];for(c=0;c<a.length;c++)b.push("arg"+b.length+"_"+pb++);c=a.apply(l,b.map(function(a){return qb(a)}));c instanceof r||d(new C("ReQL function must return ReQL expression"))}else c=arguments[arguments.length-1],b=Array.prototype.slice.call(arguments,0,arguments.length-1);c=q(c);b.forEach(function(a){return w(a,"string")});return y(da,b,c)}p.q("rethinkdb.fn",ea);function R(a,b,c,e){this.hc=a;this.nb=b;this.lb=e||l;this.a=c}
p.e(R,z);R.prototype.compile=function(a){var b=new L;b.g(this.hc);this.lb&&this.lb(b);var c=new Oa;E(c,1,b);for(var e in this.nb)b=this.nb[e].compile(a),H(c,2,b);a=new K;a.g(3);E(a,4,c);return a};function rb(a,b){z.prototype[b]=function(c){x(arguments,1);c=q(c);return y(R,a,[this,c],sb(b,this,c))}}function tb(a,b){z.prototype[b]=function(c){x(arguments,1);c=q(c);return y(R,Sa,[this,c],sb(b,this,c),function(b){E(b,4,a)})}}rb(14,"add");rb(15,"sub");rb(16,"mul");rb(17,"div");rb(18,"mod");tb(1,"eq");
tb(2,"ne");tb(3,"lt");tb(4,"le");tb(5,"gt");tb(6,"ge");z.prototype.eb=function(){return y(R,1,[this],sb("not",this))};p.f(z.prototype,"not",z.prototype.eb);z.prototype.count=function(){return y(R,26,[this],sb("count",this))};p.f(z.prototype,"count",z.prototype.count);z.prototype.mb=function(a){x(arguments,1);a=q(a);return y(R,36,[this,a],sb("and",this,a))};p.f(z.prototype,"and",z.prototype.mb);z.prototype.Mb=function(a){x(arguments,1);a=q(a);return y(R,35,[this,a],sb("or",this,a))};
p.f(z.prototype,"or",z.prototype.Mb);z.prototype.ec=function(a,b,c){x(arguments,2);a=q(a);b=q(b);w(c,"string");var e=c?c:"id";return y(R,37,[this],sb("between",this,a,b,"'"+e+"'"),function(c,g){var h=new Za;h.V(e);var j=a.compile(g);E(h,2,j);j=b.compile(g);E(h,3,j);E(c,11,h)})};p.f(z.prototype,"between",z.prototype.ec);z.prototype.append=function(a){x(arguments,1);a=q(a);return y(R,9,[this,a],sb("append",this,a))};p.f(z.prototype,"append",z.prototype.append);
function ub(a,b,c){b=q(b);c=c?q(c):new ka(l);R.call(this,11,[a,b,c],function(e){if(e){var f=e[0].split(":");f[1]=parseInt(f[1],10);e.shift();return 0===f[1]?a.a(e)+Q(".slice("+b.a()+(c?", "+c.a():"")+")"):1===f[1]?Q(a.a()+".slice(")+b.a(e)+Q((c?", "+c.a():"")+")"):Q(a.a()+".slice("+b.a(e)+", ")+c.a(e)+" "}return a.a()+".slice("+b.a()+(c?", "+c.a():"")+")"})}p.e(ub,R);z.prototype.slice=function(a,b){x(arguments,1);return y(ub,this,a,b)};p.f(z.prototype,"slice",z.prototype.slice);
z.prototype.Dc=function(a){x(arguments,1);return y(ub,this,0,a)};p.f(z.prototype,"limit",z.prototype.Dc);z.prototype.Wc=function(a){x(arguments,1);return y(ub,this,a)};p.f(z.prototype,"skip",z.prototype.Wc);z.prototype.Kc=function(a){x(arguments,1);a=q(a);return y(R,28,[this,a],sb("nth",this,a))};p.f(z.prototype,"nth",z.prototype.Kc);
z.prototype.filter=function(a){var b;if("object"===typeof a&&!(a instanceof r)){var c=[],e;for(e in a)a.hasOwnProperty(e)&&c.push(ca(e).eq(t(a[e])));b=y(da,[""],y(R,36,c,function(a){var b=c.map(function(a){return a.a()});if(a){var e=a[0].split(":");a.shift();b=b.map(Q);b[e[1]]=c[e[1]].a(a);return b.join("      ")}return b.join(").and(")}))}else b=v(a);var f=this;return y(R,20,[this],function(a){if(a){if("predicate"===a[0])return a.shift(),Q(f.a()+".filter(")+b.a(a)+" ";a.shift();return f.a(a)+Q(".filter("+
b.a(a)+")")}return f.a()+".filter("+b.a()+")"},function(a,c){var e=new ab;e.S(b.w[0]);e.D(b.body.compile(c));var f=new Ua;E(f,1,e);E(a,5,f)})};p.f(z.prototype,"filter",z.prototype.filter);
z.prototype.map=function(a){var a=v(a),b=this;return y(R,21,[this],function(c){if(c){if("arg:0"===c[0])return c.shift(),b.a(c)+Q(".map("+a.a(c)+")");c.shift();return Q(b.a()+".map(")+a.a(c)+" "}return b.a()+".map("+a.a()+")"},function(b,e){var f=new N;f.S(a.w[0]);f.D(a.body.compile(e));var g=new Va;g.P(f);E(b,6,g)})};p.f(z.prototype,"map",z.prototype.map);
z.prototype.Lc=function(a){x(arguments,1);var b=Array.prototype.slice.call(arguments,0);b.forEach(function(a){w(a,"string")});var c=this;return y(R,23,[this],function(a){var f=b.map(function(a){return"'"+a+"'"});return a?"order_by"===a.shift()?Q(c.a()+".orderBy(")+P(f.join(", "))+" ":c.a(a)+Q(".orderBy("+f.join(", ")+")"):c.a()+".orderBy("+f.join(", ")+")"},function(a){for(var c=0;c<b.length;c++){var g=k,h=b[c];"-"===h[0]&&(g=m,h=h.slice(1));var j=new Xa;j.ua(h);E(j,2,g);H(a,8,j)}})};
p.f(z.prototype,"orderBy",z.prototype.Lc);z.prototype.pc=function(a){w(a,"string");var b=a?this.map(ca(a)):this;return y(R,24,[b],function(a){return a?(a.shift(),b.a(a)+"           "):b.a()+".distinct()"})};p.f(z.prototype,"distinct",z.prototype.pc);
z.prototype.reduce=function(a,b){x(arguments,2);var a=q(a),b=v(b),c=this;return y(R,31,[this],function(e){if(e)if("reduce"===e[0]){e.shift();if("body"===e[0])return e.shift(),Q(c.a()+".reduce("+a.a()+", ")+b.a(e)+" ";if("base"===e[0])return e.shift(),Q(c.a()+".reduce(")+a.a(e)+Q(", "+b.a()+")")}else return e.shift(),c.a(e)+Q(".reduce("+a.a()+", "+b.a()+")");else return c.a()+".reduce("+a.a()+", "+b.a()+")"},function(c,f){var g=new $a,h=a.compile(f);E(g,1,h);E(g,2,b.w[0]);E(g,3,b.w[1]);g.D(b.body.compile(f));
E(c,9,g)})};p.f(z.prototype,"reduce",z.prototype.reduce);
z.prototype.Cb=function(a,b,c,e){x(arguments,4);var a=v(a),b=v(b),c=q(c),e=v(e),f=this;return y(R,32,[this],function(g){var h=f.a(),j=a.a(),u=b.a(),s=c.a(),B=e.a();if(g){var M=g.shift();if("arg:0"===M)return f.a(g)+Q(".groupedMapReduce("+j+", "+u+", "+s+", "+B+")");if("group_mapping"===M)return Q(h+".groupedMapReduce(")+a.a(g)+Q(", "+u+", "+s+", "+B+")");if("value_mapping"===M)return Q(h+".groupedMapReduce("+j+", ")+b.a(g)+Q(", "+s+", "+B+")");M=g.shift();return"base"===M?Q(h+".groupedMapReduce("+
j+", "+u+", ")+c.a(g)+Q(", "+B+")"):Q(h+".groupedMapReduce("+j+", "+u+", "+s+", ")+e.a(g)+" "}return h+".groupedMapReduce("+j+", "+u+", "+s+", "+B+")"},function(f,h){var j=new N;j.S(a.w[0]);j.D(a.body.compile(h));var u=new N;u.S(b.w[0]);u.D(b.body.compile(h));var s=new $a,B=c.compile(h);E(s,1,B);E(s,2,e.w[0]);E(s,3,e.w[1]);s.D(e.body.compile(h));B=new Ya;E(B,1,j);E(B,2,u);E(B,3,s);E(f,10,B)})};p.f(z.prototype,"groupedMapReduce",z.prototype.Cb);
z.prototype.yc=function(a){x(arguments,2);var b=Array.prototype.slice.call(arguments,0,-1);b.forEach(function(a){w(a,"string")});var c=arguments[arguments.length-1];w(c,"object");var e=ea(function(a){return 1<b.length?t(b.map(a)):a(b[0])}),f=c.mapping||ea(aa()),g=c.base,h=c.reduction;h||d(new C("Must provide a reduction to groupby"));g===i&&d(new C("Must provide a base for the reduction in groupby"));var e=this.Cb(e,f,g,h),j=c.finalizer;j&&(e=e.map(function(a){return a.bb({reduction:j(a("reduction"))})}));
return e};p.f(z.prototype,"groupBy",z.prototype.yc);p.q("rethinkdb.count",{mapping:function(){return t(1)},base:0,reduction:function(a,b){return a.add(b)}});p.q("rethinkdb.sum",function(a){x(arguments,1);w(a,"string");return{mapping:function(b){return b(a)},base:0,reduction:function(a,c){return a.add(c)}}});
p.q("rethinkdb.average",function(a){x(arguments,1);w(a,"string");return{mapping:function(b){return t([b(a),1])},base:[0,0],reduction:function(a,c){return t([a.nth(0).add(c.nth(0)),a.nth(1).add(c.nth(1))])},finalizer:function(a){return a.nth(0).div(a.nth(1))}}});z.prototype.contains=function(a){w(a,"string");var b=this;return y(R,4,[this],function(c){return c?"arg:0"===c.shift()?b.a(c)+Q(".contains("+a+")"):Q(b.a())+P(".contains("+a+")"):b.a()+".contains("+a+")"},function(b){b.ua(a)})};
p.f(z.prototype,"contains",z.prototype.contains);z.prototype.Ga=function(a){w(a,"string");var b=this;return y(R,2,[this],function(c){return c?"arg:0"===c[0]?(c.shift(),b.a(c)):Q(b.a())+P("('"+a+"')"):b.a()+"('"+a+"')"},function(b){b.ua(a)})};p.f(z.prototype,"getAttr",z.prototype.Ga);
z.prototype.Nb=function(){var a=Array.prototype.slice.call(arguments,0);p.isArray(a)||(a=[a]);a.forEach(function(a){w(a,"string")});var b=this;return y(R,6,[this],function(c){var e=a.map(function(a){return"'"+a+"'"});return c?(c.shift(),b.a(c)+Q(".pick("+e.join(", ")+")")):b.a()+".pick("+e.join(", ")+")"},function(b){for(var e in a)H(b,3,a[e])})};p.f(z.prototype,"pick",z.prototype.Nb);
z.prototype.Tb=function(a){p.isArray(a)||(a=[a]);a.forEach(function(a){w(a,"string")});var b=this;return y(R,39,[this],function(c){var e=a.map(function(a){return"'"+a+"'"});return c?(c.shift(),b.a(c)+Q(".unpick("+e.join(", ")+")")):b.a()+".unpick("+e.join(", ")+")"},function(b){for(var e in a)H(b,3,a[e])})};p.f(z.prototype,"unpick",z.prototype.Tb);z.prototype.Pc=function(){var a=Array.prototype.slice.call(arguments,0);return this.map(function(b){return z.prototype.Nb.apply(b,a)})};
p.f(z.prototype,"pluck",z.prototype.Pc);z.prototype.ld=function(){var a=Array.prototype.slice.call(arguments,0);return this.map(function(b){return z.prototype.Tb.apply(b,a)})};p.f(z.prototype,"without",z.prototype.ld);function vb(a){this.Ub=a}p.e(vb,z);vb.prototype.compile=function(){var a=new K;a.g(1);a.na(this.Ub);return a};vb.prototype.a=function(a){var b="r.letVar('"+this.Ub+"')";return a?P(b):b};function wb(){}p.e(wb,z);wb.prototype.compile=function(){var a=new K;a.g(15);return a};
wb.prototype.a=function(a){return a?"^^^^^^^^":"r.R('@')"};function xb(a,b){R.call(this,2,[a],function(c){return c?"arg:0"===c.shift()?a.a(c)+"('"+b+"')":Q(a.a())+P("('"+b+"')"):a.a()+"('"+b+"')"},function(a){a.ua(b)})}p.e(xb,R);function ca(a){w(a,"string");var a=a.split("."),b=a.shift();"@"===b[0]&&1<b.length?a.unshift(b.slice(1)):"@"!==b[0]&&a.unshift(b);for(var c=y(wb);b=a.shift();)c=y(xb,c,b);return c}p.q("rethinkdb.R",ca);
function qb(a){w(a,"string");for(var a=a.split("."),b=a.shift(),c=y(vb,b);b=a.shift();)c=y(xb,c,b);return c}p.q("rethinkdb.letVar",qb);z.prototype.bb=function(a){var a=q(a),b=this;return y(R,8,[this,a],function(c){if(c){var e=c.shift();return"arg:0"===e?b.a(c)+Q(".merge("+a.a()+")"):"arg:1"===e?Q(b.a()+".merge(")+a.a(c)+" ":P(b.a()+".merge("+a.a()+")")}return b.a()+".merge("+a.a()+")"})};p.f(z.prototype,"merge",z.prototype.bb);
z.prototype.Sb=function(a){x(arguments,1);var b=Array.prototype.slice.call(arguments,0).map(q),c=this;return y(R,27,[this].concat(b),function(a){var f=b.map(function(a){return a.a()});if(a){var g=a.shift();if(g){if("arg:0"===g)return c.a(a)+Q(".union("+f.join(", ")+")");g=parseInt(g.split(":")[1],10);f=f.map(Q);f[g]=b[g].a(a);return Q(c.a()+".union(")+f.join("  ")+" "}return P(c.a()+".union("+f.join(", ")+")")}return c.a()+".union("+f.join(", ")+")"})};p.f(z.prototype,"union",z.prototype.Sb);
z.prototype.ia=function(a){var a=v(a),b=this;return y(R,22,[this],function(c){return c?"arg:0"===c.shift()?b.a(c)+Q(".concatMap("+a.a()+")"):Q(b.a()+".concatMap(")+a.a(c)+" ":b.a()+".concatMap("+a.a()+")"},function(b,e){var f=new N;f.S(a.w[0]);f.D(a.body.compile(e));var g=new Wa;g.P(f);E(b,7,g)})};p.f(z.prototype,"concatMap",z.prototype.ia);function yb(a,b,c){this.Qa=a;this.Ra=b;this.Ea=c}p.e(yb,z);
yb.prototype.compile=function(a){var b=new Pa,c=this.Qa.compile(a);E(b,1,c);c=this.Ra.compile(a);E(b,2,c);a=this.Ea.compile(a);E(b,3,a);a=new K;a.g(4);E(a,5,b);return a};
yb.prototype.a=function(a){if(a){var b=a.shift(),c=Q(this.Qa.a()),e=Q(this.Ra.a()),f=Q(this.Ea.a());if("test"===b)c=this.Qa.a(a);else if("true"===b)e=this.Ra.a(a);else if("false"===b)f=this.Ea.a(a);else return P("             "+c+"  "+e+"  "+f+" ");return"             "+c+"  "+e+"  "+f+" "}return"r.branch("+this.Qa.a()+", "+this.Ra.a()+", "+this.Ea.a()+")"};function zb(a,b,c){w(b,r);w(c,r);a=q(a);return y(yb,a,b,c)}p.q("rethinkdb.branch",zb);function Ab(a,b){this.ga=a;this.Ta=b}p.e(Ab,z);
Ab.prototype.compile=function(a){var b=new Na,c;for(c in this.ga)if(this.ga.hasOwnProperty(c)){var e=this.ga[c],f=new La;f.na(c);f.Oa(e.compile(a));H(b,1,f)}a=this.Ta.compile(a);E(b,2,a);a=new K;a.g(2);E(a,3,b);return a};
Ab.prototype.a=function(a){var b=[],c;for(c in this.ga)this.ga.hasOwnProperty(c)&&b.push([c,this.ga[c]]);if(a){var e=a.shift().split(":")[1],b=b.map(function(b){return b[0]===e?Q("'"+b[0]+"':")+b[1].a(a):Q("'"+b[0]+"':"+b[1].a())});return Q("r.let({")+b.join("  ")+Q("}, "+this.Ta.a()+")")}b=b.map(function(a){return"'"+a[0]+"':"+a[1].a()});return"r.let({"+b.join(", ")+"}, "+this.Ta.a()+")"};function Bb(a,b){w(b,r);for(var c in a)a.hasOwnProperty(c)&&w(a[c],z);return y(Ab,a,b)}p.q("rethinkdb.let",Bb);
function Cb(a,b){this.ab=a;this.Fa=b}p.e(Cb,r);Cb.prototype.B=function(a){var b=new fb,c=this.ab.compile(a);E(b,1,c);b.na(this.Fa.w[0]);a=this.Fa.body.B(a);(a=G(a,4))||d(new C("For each requires a write query to execute"));H(b,3,a);a=new O;a.g(6);E(a,7,b);b=new D;b.g(2);E(b,4,a);return b};Cb.prototype.a=function(a){return a?(a.shift(),this.ab.a(a)+Q(".forEach("+this.Fa.a()+")")):this.ab.a()+".forEach("+this.Fa.a()+")"};z.prototype.forEach=function(a){a=v(a);return y(Cb,this,a)};
p.f(z.prototype,"forEach",z.prototype.forEach);z.prototype.Ac=function(a,b){return this.ia(function(c){return a.ia(function(a){return zb(b(c,a),t([{left:c,right:a}]),t([]))})})};p.f(z.prototype,"innerJoin",z.prototype.Ac);z.prototype.Mc=function(a,b){return this.ia(function(c){return Bb({matches:a.ia(function(a){return zb(b(c,a),t([{left:c,right:a}]),t([]))}).Pb()},zb(qb("matches").count().gt(0),qb("matches"),t([{left:c}])))})};p.f(z.prototype,"outerJoin",z.prototype.Mc);
z.prototype.qc=function(a,b){return this.ia(function(c){return Bb({right:b.get(c(a))},zb(qb("right").ne(t(l)),t([{left:c,right:qb("right")}]),t([])))})};p.f(z.prototype,"equiJoin",z.prototype.qc);z.prototype.Vb=function(){return this.map(function(a){return zb(a.contains("right"),a("left").bb(a("right")),a("left"))})};p.f(z.prototype,"zip",z.prototype.Vb);z.prototype.Pb=function(){var a=this;return y(R,29,[this],function(b){return b?(b.shift(),a.a(b)+"                "):a.a()+".streamToArray()"})};
p.f(z.prototype,"streamToArray",z.prototype.Pb);z.prototype.dc=function(){var a=this;return y(R,30,[this],function(b){return b?(b.shift(),a.a(b)+"                "):a.a()+".arrayToStream()"})};p.f(z.prototype,"arrayToStream",z.prototype.dc);function A(a,b,c){this.L=a;this.N=b;this.bc="boolean"===typeof c?c:l}p.e(A,z);A.prototype.compile=function(a){var b=new K;b.g(13);var c=new Ra,e=new J;e.va(this.N||ma.N);E(e,2,this.L);E(e,3,this.bc!==l?this.Se:a&&a.vb!==i?a.vb:m);c.F(e);E(b,15,c);return b};A.prototype.a=function(a){return a?this.N?P("r.db('"+this.N+"').table('"+this.L+"')"):P("r.table('"+this.L+"')"):this.N?"r.db('"+this.N+"').table('"+this.L+"')":"r.table('"+this.L+"')"};function Db(a,b,c){this.l=a;this.r=b;this.m=c||"id"}
p.e(Db,z);Db.prototype.compile=function(a){var b=this.l.compile(a),c=G(b,15).O(),b=new Qa;b.F(c);b.V(this.m);b.fa(this.r.compile(a));a=new K;a.g(12);E(a,14,b);return a};Db.prototype.a=function(a){if(a){var b=a.shift();return"key"===b?Q(this.l.a()+".get(")+this.r.a(a)+Q(", '"+this.m+"')"):"attrname"===b?Q(this.l.a()+".get("+this.r.a()+", ")+P("'"+this.m+"'")+" ":this.l.a(a)+Q(".get("+this.r.a()+", '"+this.m+"')")}return this.l.a()+".get("+this.r.a()+", '"+this.m+"')"};
A.prototype.get=function(a,b){x(arguments,1);a=q(a);return y(Db,this,a,b)};p.f(A.prototype,"get",A.prototype.get);function Eb(a,b){this.l=a;this.Ba=b}p.e(Eb,r);Eb.prototype.B=function(a){var b=this.l.compile(a),c=G(b,15).O(),b=new eb;b.F(c);for(c=0;c<this.Ba.length;c++){var e=this.Ba[c].compile(a);H(b,2,e)}a=new O;a.g(4);E(a,5,b);b=new D;b.g(2);E(b,4,a);return b};
Eb.prototype.a=function(a){var b=this.Ba.map(function(a){return a.a()});if(a){var b=b.map(Q),c=a.shift(),e;c!==i?(e=Q(this.l.a()),c=parseInt(c.split(":")[1],10),b[c]=this.Ba[c].a(a)):e=this.l.a(a);a=" "+b.join("  ")+" ";return e+"        "+a+" "}a="["+b.join(", ")+"]";return this.l.a()+".insert("+a+")"};A.prototype.Eb=function(a){x(arguments,1);p.isArray(a)||(a=[a]);a=a.map(t);return new Eb(this,a)};p.f(A.prototype,"insert",A.prototype.Eb);function Fb(a){this.I=a}p.e(Fb,r);
Fb.prototype.B=function(a){var b=new cb;b.wa(this.I.compile(a));a=new O;a.g(2);E(a,3,b);b=new D;b.g(2);E(b,4,a);return b};Fb.prototype.a=function(a){return a?(a.shift(),this.I.a(a)+"      "):this.I.a()+".del()"};function Gb(a,b,c){this.l=a;this.r=b;this.m=c||"id"}p.e(Gb,r);Gb.prototype.B=function(a){var b=new hb;b.F(Ma(this.l.compile(a)).O());b.V(this.m);b.fa(this.r.compile(a));a=new O;a.g(8);E(a,9,b);b=new D;b.g(2);E(b,4,a);return b};
Gb.prototype.a=function(a){return a?a.shift()!==i?Q(this.l.a()+".get(")+this.r.a(a)+"       ":this.l.a(a)+Q(".get("+this.r.a()+").del()"):this.l.a()+".get("+this.r.a()+").del()"};z.prototype.nc=function(){0<arguments.length&&d(new TypeError("Method del does not take any arguments. Calling del directly on a table reference will delete the whole table. Tod delete a single row call table.get(key).del()"));return this instanceof Db?new Gb(this.l,this.r,this.m):new Fb(this)};p.f(z.prototype,"del",z.prototype.nc);
function Hb(a,b,c){this.I=a;this.s=b;this.ca=c}p.e(Hb,r);Hb.prototype.B=function(a){var b=new N;b.S(this.s.w[0]);b.D(this.s.body.compile(a));var c=new bb;c.wa(this.I.compile(a));c.P(b);a=new O;a.g(1);E(a,2,c);E(a,11,!this.ca);c=new D;c.g(2);E(c,4,a);return c};Hb.prototype.a=function(a){return a?"view"===a.shift()?this.I.a(a)+Q(".update("+this.s.a()+")"):Q(this.I.a()+".update(")+this.s.a(a)+" ":this.I.a()+".update("+this.s.a()+")"};
function Ib(a,b,c,e,f){this.l=a;this.r=b;this.m=c||"id";this.s=e;this.ca=f}p.e(Ib,r);Ib.prototype.B=function(a){var b=new N;b.S(this.s.w[0]);b.D(this.s.body.compile(a));var c=new gb;c.F(Ma(this.l.compile(a)).O());c.V(this.m);c.fa(this.r.compile(a));c.P(b);a=new O;a.g(7);E(a,8,c);E(a,11,!this.ca);c=new D;c.g(2);E(c,4,a);return c};
Ib.prototype.a=function(a){if(a){var b=a.shift();return b===i?this.l.a(a)+Q(".get("+this.r.a()+", '"+this.m+"').update("+this.s.a()+")"):"key"===b?Q(this.l.a()+".get(")+this.r.a(a)+Q(", '"+this.m+"').update("+this.s.a()+")"):"keyname"===b?Q(this.l.a()+".get("+this.r.a()+", ")+P("'"+this.m+"'")+Q(").update("+this.s.a()+")"):Q(this.l.a()+".get("+this.r.a()+", '"+this.m+"').update(")+this.s.a(a)+" "}return this.l.a()+".get("+this.r.a()+", '"+this.m+"').update("+this.s.a()+")"};
z.prototype.update=function(a,b){x(arguments,1);a=v(a);b=b===i?m:b;return this instanceof Db?new Ib(this.l,this.r,this.m,a,b):new Hb(this,a,b)};p.f(z.prototype,"update",z.prototype.update);function Jb(a,b,c){this.I=a;this.s=b;this.ca=c}p.e(Jb,r);Jb.prototype.B=function(a){var b=new N;b.S(this.s.w[0]);b.D(this.s.body.compile(a));var c=new db;c.wa(this.I.compile(a));c.P(b);a=new O;a.g(3);E(a,4,c);E(a,11,!this.ca);c=new D;c.g(2);E(c,4,a);return c};
Jb.prototype.a=function(a){return a?"view"===a.shift()?this.I.a(a)+Q(".replace("+this.s.a()+")"):Q(this.I.a()+".replace(")+this.s.a(a)+" ":this.I.a()+".replace("+this.s.a()+")"};function Kb(a,b,c,e,f){this.l=a;this.r=b;this.m=c||"id";this.s=e;this.ca=f}p.e(Kb,r);Kb.prototype.B=function(a){var b=new N;b.S(this.s.w[0]);b.D(this.s.body.compile(a));var c=new ib;c.F(Ma(this.l.compile(a)).O());c.V(this.m);c.fa(this.r.compile(a));c.P(b);a=new O;a.g(9);E(a,10,c);E(a,11,!this.ca);c=new D;c.g(2);E(c,4,a);return c};
Kb.prototype.a=function(a){if(a){var b=a.shift();return b===i?this.l.a(a)+Q(".get("+this.r.a()+", '"+this.m+"').mutate("+this.s.a()+")"):"key"===b?Q(this.l.a()+".get(")+this.r.a(a)+Q(", '"+this.m+"').mutate("+this.s.a()+")"):"keyname"===b?Q(this.l.a()+".get("+this.r.a()+", ")+P("'"+this.m+"'")+Q(").mutate("+this.s.a()+")"):Q(this.l.a()+".get("+this.r.a()+", '"+this.m+"').mutate(")+this.s.a(a)+" "}return this.l.a()+".get("+this.r.a()+", '"+this.m+"').mutate("+this.s.a()+")"};
z.prototype.replace=function(a,b){x(arguments,1);a=v(a);b=b===i?m:b;return this instanceof Db?new Kb(this.l,this.r,this.m,a,b):new Jb(this,a,b)};p.f(z.prototype,"replace",z.prototype.replace);function Lb(){}Lb.prototype.zb=function(a,b){return ya(a)?Mb(this,b):b};p.Xf={};function Nb(a,b){this.n=a|0;this.j=b|0}var Ob={};function Pb(a){if(-128<=a&&128>a){var b=Ob[a];if(b)return b}b=new Nb(a|0,0>a?-1:0);-128<=a&&128>a&&(Ob[a]=b);return b}function S(a){return isNaN(a)||!isFinite(a)?Qb:a<=-Rb?T:a+1>=Rb?Sb:0>a?U(S(-a)):new Nb(a%Tb|0,a/Tb|0)}function V(a,b){return new Nb(a,b)}var Tb=4294967296,Rb=Tb*Tb/2,Qb=Pb(0),Ub=Pb(1),Vb=Pb(-1),Sb=V(-1,2147483647),T=V(0,-2147483648),Wb=Pb(16777216);n=Nb.prototype;n.ya=function(){return this.j*Tb+Xb(this)};
n.toString=function(a){a=a||10;(2>a||36<a)&&d(Error("radix out of range: "+a));if(Yb(this))return"0";if(0>this.j){if(this.z(T)){var b=S(a),c=Zb(this,b),b=$b(c.multiply(b),this);return c.toString(a)+b.n.toString(a)}return"-"+U(this).toString(a)}for(var c=S(Math.pow(a,6)),b=this,e="";;){var f=Zb(b,c),g=$b(b,f.multiply(c)).n.toString(a),b=f;if(Yb(b))return g+e;for(;6>g.length;)g="0"+g;e=""+g+e}};function Xb(a){return 0<=a.n?a.n:Tb+a.n}function Yb(a){return 0==a.j&&0==a.n}
n.z=function(a){return this.j==a.j&&this.n==a.n};n.ha=function(a){if(this.z(a))return 0;var b=0>this.j,c=0>a.j;return b&&!c?-1:!b&&c?1:0>$b(this,a).j?-1:1};function U(a){return a.z(T)?T:a.eb().add(Ub)}n.add=function(a){var b=this.j>>>16,c=this.j&65535,e=this.n>>>16,f=a.j>>>16,g=a.j&65535,h=a.n>>>16,j;j=0+((this.n&65535)+(a.n&65535));a=0+(j>>>16);a+=e+h;e=0+(a>>>16);e+=c+g;c=0+(e>>>16);c=c+(b+f)&65535;return V((a&65535)<<16|j&65535,c<<16|e&65535)};function $b(a,b){return a.add(U(b))}
n.multiply=function(a){if(Yb(this)||Yb(a))return Qb;if(this.z(T))return 1==(a.n&1)?T:Qb;if(a.z(T))return 1==(this.n&1)?T:Qb;if(0>this.j)return 0>a.j?U(this).multiply(U(a)):U(U(this).multiply(a));if(0>a.j)return U(this.multiply(U(a)));if(0>this.ha(Wb)&&0>a.ha(Wb))return S(this.ya()*a.ya());var b=this.j>>>16,c=this.j&65535,e=this.n>>>16,f=this.n&65535,g=a.j>>>16,h=a.j&65535,j=a.n>>>16,a=a.n&65535,u,s,B,M;M=0+f*a;B=0+(M>>>16);B+=e*a;s=0+(B>>>16);B=(B&65535)+f*j;s+=B>>>16;B&=65535;s+=c*a;u=0+(s>>>16);
s=(s&65535)+e*j;u+=s>>>16;s&=65535;s+=f*h;u+=s>>>16;s&=65535;u=u+(b*a+c*j+e*h+f*g)&65535;return V(B<<16|M&65535,u<<16|s)};
function Zb(a,b){Yb(b)&&d(Error("division by zero"));if(Yb(a))return Qb;if(a.z(T)){if(b.z(Ub)||b.z(Vb))return T;if(b.z(T))return Ub;var c=Zb(ac(a,1),b).shiftLeft(1);if(c.z(Qb))return 0>b.j?Ub:Vb;var e=$b(a,b.multiply(c));return c.add(Zb(e,b))}if(b.z(T))return Qb;if(0>a.j)return 0>b.j?Zb(U(a),U(b)):U(Zb(U(a),b));if(0>b.j)return U(Zb(a,U(b)));for(var f=Qb,e=a;0<=e.ha(b);){for(var c=Math.max(1,Math.floor(e.ya()/b.ya())),g=Math.ceil(Math.log(c)/Math.LN2),g=48>=g?1:Math.pow(2,g-48),h=S(c),j=h.multiply(b);0>
j.j||0<j.ha(e);)c-=g,h=S(c),j=h.multiply(b);Yb(h)&&(h=Ub);f=f.add(h);e=$b(e,j)}return f}n.eb=function(){return V(~this.n,~this.j)};n.mb=function(a){return V(this.n&a.n,this.j&a.j)};n.Mb=function(a){return V(this.n|a.n,this.j|a.j)};function bc(a,b){return V(a.n^b.n,a.j^b.j)}n.shiftLeft=function(a){a&=63;if(0==a)return this;var b=this.n;return 32>a?V(b<<a,this.j<<a|b>>>32-a):V(0,b<<a-32)};function ac(a,b){b&=63;if(0==b)return a;var c=a.j;return 32>b?V(a.n>>>b|c<<32-b,c>>b):V(c>>b-32,0<=c?0:-1)};function cc(a){for(var b=[],c=0;c<a.length;c++)b.push(String.fromCharCode(a[c]));return b.join("")}function dc(a){return new Uint8Array(Array.prototype.map.call(a,function(a){return a.charCodeAt(0)}))}function ec(){this.J=0}p.e(ec,Lb);function W(a){d(new qa("Error deserializing incorrectly formated message, "+a))}
function Mb(a,b){for(var c=Ba(b.ja()),e=[],f=0,g=0;g<c.length;g++){var h=c[g];if(Ca(b,h)){var j=0;do{var u=a.zb(h,b.get(h,j));e.push(u);f+=u.byteLength;j++}while(h.$&&j<b.tb(h))}}c=new Uint8Array(f);for(g=f=0;g<e.length;g++)h=e[g],c.set(new Uint8Array(h),f),f+=h.byteLength;return c}
ec.prototype.zb=function(a,b){var c=a.K,e=fc[c],f=gc(S(a.G<<3|e)),g;switch(e){case X:var h=S(b);if(c==xa||17==c)h=bc(h.shiftLeft(1),ac(h,63));g=gc(h);break;case hc:h=new ArrayBuffer(8);c=new DataView(h);switch(a.K){case 1:c.setFloat64(0,b,k);break;case va:g=S(b);c.setUint32(0,Xb(g),k);c.setUint32(4,g.j,k);break;case wa:g=S(b);c.setUint32(0,Xb(g),k);c.setInt32(4,g.j,k);break;default:W("Unexpected field type")}g=new Uint8Array(h);break;case ic:switch(a.K){case 11:h=Mb(this,b);break;case 9:h=dc(unescape(encodeURIComponent(b)));
break;case 12:h=dc(b);break;default:W("Unexpected field type")}g=h.length;c=gc(S(g));g=new Uint8Array(c.length+g);g.set(c,0);g.set(h,c.length);break;case jc:W("Use of Groups deprecated and not supported");break;case kc:h=new ArrayBuffer(4);c=new DataView(h);switch(a.K){case 2:c.setFloat32(0,b,k);break;case 7:c.setUint32(0,b,k);break;case 15:c.setInt32(0,b,k);break;default:W("Unexpected field type")}g=new Uint8Array(h);break;default:W("Unexpected wire type")}h=new Uint8Array(f.length+g.length);h.set(new Uint8Array(f),
0);h.set(new Uint8Array(g),f.length);return h};function gc(a){function b(a){var e=S(128),e=$b(a,Zb(a,e).multiply(e)).n,f=S(127);0<a.ha(f)?(e+=128,a=b(ac(a,7)),a.unshift(e)):a=[e];return a}a=b(a);return new Uint8Array(a)}
function lc(a,b,c){var e=b.ja();for(a.J=0;a.J<c.length;){var f=mc(a,c),g=f%8,h;h=e;f>>=3;p.h.i.assert(p.c.$a(f));h=h.Y[parseInt(f,10)]||l;var j=a,u=g,f=h,g=c,s=i;switch(u){case X:g=mc(j,g);if(f){j=i;switch(f.K){case ta:case ua:j=g.toString();break;case 5:case 13:case 14:j=g;break;case 17:g=S(g);j=bc(ac(g,1),g.shiftLeft(63)).n;break;case xa:g=S(g);j=bc(ac(g,1),g.shiftLeft(63)).toString();break;case 8:j=0===j?m:k;break;default:W("Unexpected field type")}s=j}else s=l;break;case ic:u=mc(j,g);g=new Uint8Array(g.buffer,
g.byteOffset+j.J,u);j.J+=u;if(f){j=i;switch(f.K){case 9:j=decodeURIComponent(escape(cc(g)));break;case 12:j=cc(g);break;case 11:j=new ec;p.h.i.assert(ya(f),"Expected message or group");f=new f.cb.A.Gc;lc(j,f,g);p.h.i.assert(f instanceof F);j=f;break;default:W("Unexpected field type")}s=j}else s=l;break;case kc:g=new DataView(g.buffer,g.byteOffset+j.J,4);j.J+=4;if(f){j=i;switch(f.K){case 2:j=g.getFloat32(0,k);break;case 7:j=g.getUint32(0,k);break;case 15:j=g.getInt32(0,k);break;default:W("Unexpected field type")}s=
j}else s=l;break;case hc:g=new DataView(g.buffer,g.byteOffset+j.J,8);j.J+=8;if(f){j=i;switch(f.K){case 1:j=g.getFloat64(0,k);break;case va:j=(new Nb(g.getUint32(0,k),g.getUint32(4,k))).toString();break;case wa:j=(new Nb(g.getUint32(0,k),g.getInt32(4,k))).toString();break;default:W("Unexpected field type")}s=j}else s=l;break;default:W("Unexpected wire type of "+u)}g=s;h!=l&&g!=l&&(h.$?b.add(h,g):b.set(h,g))}}function mc(a,b){var c=b[a.J++];if(127<c)var c=c-128,e=mc(a,b),c=c+(e<<7);return c}
var X=0,hc=1,ic=2,jc=3,kc=5,fc=[-1,hc,kc,X,X,X,hc,kc,X,ic,jc,ic,ic,X,X,kc,hc,X,X];function nc(a){this.name="Runtime Error";this.message=a||"The RDB runtime experienced an error"}p.e(nc,Error);p.q("rethinkdb.errors.RuntimeError",nc);function oc(a){this.name="Broken Client";this.message=a||"The client sent the server an incorrectly formatted message"}p.e(oc,Error);p.q("rethinkdb.errors.BrokenClient",oc);function pc(a){this.name="Bad Query";this.message=a||"This query contains type errors"}p.e(pc,Error);p.q("rethinkdb.errors.BadQuery",pc);
function C(a){this.name="RDB Client Error";this.message=a||"The RDB client has experienced an error"}p.e(C,Error);p.q("rethinkdb.errors.ClientError",C);
function sb(a,b,c){var e=Array.prototype.slice.call(arguments,2);return function(c){var g=e.map(function(a){return a instanceof r?a.a():a.toString()}),h=b.a()+"."+a+"("+g.join(", ")+")";if(c){if(0===c.length)return P(h);h=c.shift();"lowerbound"===h?h="arg:1":"upperbound"===h&&(h="arg:2");var j=h.split(":");if("arg"===j[0])return j[1]=parseInt(j[1],10),g=g.map(Q),0===j[1]?h=b.a(c):(h=Q(b.a()),j=j[1]-1,c=e[j].a(c),g[j]=c),g=g.join("  "),h+" "+Q(a)+" "+g+" "}else return h}}
function Q(a){return a.replace(/./g," ")}function P(a){return a.replace(/./g,"^")};function qc(a,b,c){this.Wa=a;this.Qc=b;this.dd=c;this.sa=[];this.Za=m;this.Aa=l;this.xa=m}qc.prototype.close=function(){delete this.Wa.ka[this.dd]};qc.prototype.next=function(a){var b=this.sa.shift();b===i?this.Za?a(b):(this.Aa=p.bind(this.next,this,a),this.xa&&rc(this.Wa),this.xa=m):a(b)&&this.next(a)};p.f(qc.prototype,"next",qc.prototype.next);qc.prototype.Ua=function(a){this.Za?a(this.sa.splice(0,this.sa.length)):(this.Aa=p.bind(this.Ua,this,a),this.xa&&rc(this.Wa),this.xa=m)};
p.f(qc.prototype,"collect",qc.prototype.Ua);function sc(a,b,c){p.isArray(b)?Array.prototype.push.apply(a.sa,b):a.sa.push(b);a.Za=c;a.xa=k;a.Aa&&a.Aa()};function Y(a,b){"undefined"===typeof a?a={}:"string"===typeof a&&(a={host:a});this.Ha=a.host||this.Xb;this.Ma=a.port||this.jb;this.N=a.db||this.Wb;w(this.Ha,"string");w(this.Ma,"number");w(this.N,"string");this.ka={};this.Jc=1;this.Ca=b||l;ma=this}Y.prototype.Xb="localhost";Y.prototype.jb=28015;Y.prototype.Wb="test";Y.prototype.Sc=function(a){this.constructor.call(this,{host:this.Ha,port:this.Ma,db:this.N},a,this.Ca)};p.f(Y.prototype,"reconnect",Y.prototype.Sc);
function Z(a,b){a.Ca?a.Ca(b):a.gg?console.log(b.name+":"+b.message):d(b)}Y.prototype.Vc=function(a){this.Ca=a};p.f(Y.prototype,"setErrorHandler",Y.prototype.Vc);function tc(a,b){var c=Mb(new ec,b),e=c.byteLength,f=new Uint8Array(e+4);(new DataView(f.buffer)).setInt32(0,e,k);f.set(c,4);a.gb(f.buffer)}Y.prototype.ma=function(a,b){x(arguments,1);var c=a.B({vb:m});c.hb((this.Jc++).toString());var e=new qc(this,a,c.ea());this.ka[c.ea()]=e;tc(this,c);b&&e.next(b);return e};p.f(Y.prototype,"run",Y.prototype.ma);
function uc(a,b){(new DataView(b.buffer)).getUint32(0,k)!==b.length-4&&Z(a,new C("RDB response corrupted, length inaccurate"));var c=new ec,e=new mb;try{lc(c,e,new Uint8Array(b.buffer,4))}catch(f){Z(a,new C("response deserialization failed"))}if(c=a.ka[e.ea()])switch(G(e,1)){case 101:var g=new oc(G(e,4));sc(c,g,k);break;case 103:var g=c.Qc,h=G(e,4),e=G(e,5),j=[];e&&(j=Ha(e,1));g=h+"\n\t"+g.a()+"\n\t"+g.a(j);g=new nc(g);sc(c,g,k);break;case 102:g=new pc(G(e,4));sc(c,g,k);break;case 0:delete a.ka[e.ea()];
sc(c,[],k);break;case 3:delete a.ka[e.ea()];g=Ha(e,3).map(JSON.parse);sc(c,g,k);break;case 1:delete a.ka[e.ea()];g=JSON.parse(G(e,3,0));sc(c,g,k);break;case 2:g=Ha(e,3).map(JSON.parse);sc(c,g,m);break;default:g=new C("unknown response status code"),sc(c,g,k)}}Y.prototype.kd=function(a){x(arguments,1);w(a,"string");this.N=a};p.f(Y.prototype,"use",Y.prototype.kd);Y.prototype.wc=function(){return this.N};p.f(Y.prototype,"getDefaultDb",Y.prototype.wc);
function rc(a){var b=new D;b.g(3);b.hb(i);tc(a,b)};function vc(a,b){this.Qb=a;this.M=b||l}p.e(vc,r);vc.prototype.B=function(){var a=new jb;a.g(this.Qb);this.M&&a.va(this.M);var b=new D;b.g(5);E(b,5,a);return b};vc.prototype.a=function(a){var b=this.M?"'"+this.M+"'":"",c,e="";switch(this.Qb){case 1:c="dbCreate";break;case 2:c="dbDrop";break;case 3:c="dbList";break;case 6:c="db",e=".tableList()"}b="r."+c+"("+b+")";return a?P(b)+Q(e):b+e};p.q("rethinkdb.dbCreate",function(a){x(arguments,1);w(a,"string");return new vc(1,a)});
p.q("rethinkdb.dbDrop",function(a){x(arguments,1);w(a,"string");return new vc(2,a)});p.q("rethinkdb.dbList",function(){return new vc(3)});function $(a){this.L=a}p.q("rethinkdb.db",function(a){x(arguments,1);w(a,"string");return new $(a)});$.prototype.ad=function(){return new vc(6,this.L)};p.f($.prototype,"tableList",$.prototype.ad);function wc(a,b,c,e,f){this.qa=a;this.M=b;this.aa=c;this.m=e;this.pa=f}p.e(wc,r);
wc.prototype.B=function(){var a=new J;a.va(this.M);E(a,2,this.aa);var b=new kb;this.qa&&E(b,1,this.qa);b.F(a);this.m&&E(b,4,this.m);this.pa&&E(b,5,this.pa);a=new jb;a.g(4);E(a,3,b);b=new D;b.g(5);E(b,5,a);return b};
wc.prototype.a=function(a){var b;this.qa||this.m||this.pa?(b=[],this.qa&&b.push("dataCenter: '"+this.qa+"'"),this.m&&b.push("primaryKey: '"+this.m+"'"),this.pa&&b.push("cacheSize: '"+this.pa+"'"),this.aa&&b.push("tableName: '"+this.aa+"'"),b="{"+b.join(", ")+"}"):b="'"+this.aa+"'";b="r.db('"+this.M+"').create("+b+")";return a?P(b):b};
$.prototype.Zc=function(a){x(arguments,1);var b={};"string"===typeof a?b.tableName=a:b=a;w(b.tableName,"string");w(b.primaryKey,"string");w(b.dataCenter,"string");w(b.cacheSize,"string");return new wc(b.dataCenter,this.L,b.tableName,b.primaryKey,b.cacheSize)};p.f($.prototype,"tableCreate",$.prototype.Zc);function xc(a,b){x(arguments,1);this.M=a;this.aa=b}p.e(xc,r);xc.prototype.B=function(){var a=new J;a.va(this.M);E(a,2,this.aa);var b=new jb;b.g(5);E(b,4,a);a=new D;a.g(5);E(a,5,b);return a};
xc.prototype.a=function(a){return a?P("r.db('"+this.M+"').drop('"+this.aa+"')"):"r.db('"+this.M+"').drop('"+this.aa+"')"};$.prototype.$c=function(a){x(arguments,1);w(a,"string");return new xc(this.L,a)};p.f($.prototype,"tableDrop",$.prototype.$c);$.prototype.Yc=function(a,b){x(arguments,1);w(a,"string");w(b,"boolean");return new A(a,this.L,b)};p.f($.prototype,"table",$.prototype.Yc);function yc(a,b,c){w(b,"function");w(c,"function");Y.call(this,a,c);this.oa="";var e=this,f="http://"+this.Ha+":"+this.Ma+"/ajax/reql/",g=new XMLHttpRequest;g.open("GET",f+"open-new-connection",k);g.responseType="arraybuffer";g.onreadystatechange=function(){4===g.readyState&&(200===g.status?(e.oa=f,e.Xa=(new DataView(g.response)).getInt32(0,k),b&&b(e)):Z(e,new C("Unabled to establish HTTP connection")))};g.send()}p.e(yc,Y);p.q("rethinkdb.HttpConnection",yc);yc.prototype.jb=8080;
yc.prototype.gb=function(a){this.oa||Z(this,new C("Connection not open"));var b=new XMLHttpRequest;b.open("POST",this.oa+"?conn_id="+this.Xa,k);b.responseType="arraybuffer";var c=this;b.onreadystatechange=function(){4===b.readyState&&200===b.status&&uc(c,new Uint8Array(b.response))};b.send(a)};yc.prototype.close=function(){this.oa||Z(this,new C("Connection not open"));var a=new XMLHttpRequest;a.open("POST",this.oa+"close-connection?conn_id="+this.Xa,k);a.send();this.oa=this.Xa=l};
p.f(yc.prototype,"close",yc.prototype.close);function zc(a,b,c){Ac()||Z(this,new C("Cannot instantiate TcpConnection, TCP sockets are not available in this environment."));w(b,"function");w(c,"function");Y.call(this,a,c);this.la=l;this.ng=0;this.T=l;var e=this;e.T=l;var f=require("net").connect(this.Ma,this.Ha,function(){f.write("35ba61af","hex");f.on("data",p.bind(e.bd,e));f.on("end",function(){e.T=l;Z(e,new nc("Server disconnected"))});e.T=f;b&&b(e)});f.on("error",function(){Z(e,new C("Unabled to establish TCP connection"))})}p.e(zc,Y);
p.q("rethinkdb.TcpConnection",zc);function Ac(){return"undefined"!==typeof require&&require("net")}p.f(zc,"isAvailable",Ac);zc.prototype.gb=function(a){this.T||Z(this,new C("Connection not open"));for(var b=new Buffer(a.byteLength),c=new Uint8Array(a),e=0;e<a.byteLength;e++)b[e]=c[e];this.T.write(b)};
zc.prototype.bd=function(a){for(var a=new Uint8Array(a),b=0,c=a.byteLength;0<c;){if(this.la===l){var e=(new DataView(a.buffer,b,c)).getUint32(0,k);this.la=new Uint8Array(e+4);this.ta=0}var e=this.la.byteLength-this.ta,f=c<e?c:e,g=new Uint8Array(a.buffer,b,f);this.la.set(g,this.ta);this.ta+=f;b+=f;c-=f;e-=f;0>=e&&(e=this.la,this.la=l,this.ta=0,uc(this,e))}};
zc.prototype.close=function(){this.T||Z(this,new C("Connection not open"));var a=this;this.T.removeAllListeners("end");this.T.on("close",function(){a.T=l});this.T.end()};p.f(zc.prototype,"close",zc.prototype.close);function Bc(a){this.rc=a;Y.call(this,a,i)}p.e(Bc,Y);p.q("rethinkdb.FakeConnection",Bc);Bc.prototype.gb=function(a){a=this.rc.execute(a);uc(this,new Uint8Array(a))};p.q("rethinkdb.connect",function(a,b,c){return Ac()?new zc(a,b,c):new yc(a,b,c)});p.q("rethinkdb.fake_connect",function(a){return new Bc(a)});var ma=l;p.q("rethinkdb.lastConnection",function(){return ma});"undefined"!==typeof exports&&("undefined"!==typeof module&&module.exports?exports=module.exports=p.global.rethinkdb:exports.rethinkdb=p.global.rethinkdb);
})();
