#!/bin/bash

if [ $DATABASE == "rethinkdb" ]; then
    . `dirname "$0"`/DESCRIPTION > "$BENCH_DIR/bench_output/Insert_performance/DESCRIPTION"
    ../../build/release/rethinkdb create $SSD_DRIVES --force
fi

if [ $DATABASE == "membase" ]; then
    export PERSISTENT_DATA_DIR="$BENCH_DIR/membase_data_persistent"
fi

# Store keys in temporary file.
export TMP_KEY_FILE="$(ssh puzzler mktemp)"

mkdir -p "$BENCH_DIR/bench_output/Insert_performance"
. `dirname "$0"`/DESCRIPTION_RUN > "$BENCH_DIR/bench_output/Insert_performance/DESCRIPTION_RUN"

export -p > "$BENCH_DIR/environment"
