#!/bin/bash

mkdir -p "$BENCH_DIR/bench_output/Insert_performance"
. `dirname "$0"`/DESCRIPTION_RUN > "$BENCH_DIR/bench_output/Insert_performance/DESCRIPTION_RUN"

if [ $DATABASE == "rethinkdb" ]; then
    . `dirname "$0"`/DESCRIPTION > "$BENCH_DIR/bench_output/Insert_performance/DESCRIPTION"
fi

if [ $DATABASE == "membase" ]; then
    rm -rf $PERSISTENT_DATA_DIR
fi

# Delete temporary key file.
ssh puzzler -- rm -f "$TMP_KEY_FILE"
