// Autogenerated by metajava.py.
// Do not edit this file directly.
// The template for this file is located at:
// ../../../../../../../templates/Exception.java
package com.rethinkdb;

public class ReqlOpFailedError extends ReqlAvailabilityError {
    public ReqlOpFailedError() {}

    public ReqlOpFailedError(String message) {
        super(message);
    }

    public ReqlOpFailedError(String format, Object... args) {
        super(String.format(format, args));
    }

    public ReqlOpFailedError(String message, Throwable cause) {
        super(message, cause);
    }

    public ReqlOpFailedError(Throwable cause) {
        super(cause);
    }
}
