// Autogenerated by metajava.py.
// Do not edit this file directly.
// The template for this file is located at:
// ../../../../../../../templates/Exception.java
package com.rethinkdb;

public class ReqlDriverError extends ReqlError {
    public ReqlDriverError() {}

    public ReqlDriverError(String message) {
        super(message);
    }

    public ReqlDriverError(String format, Object... args) {
        super(String.format(format, args));
    }

    public ReqlDriverError(String message, Throwable cause) {
        super(message, cause);
    }

    public ReqlDriverError(Throwable cause) {
        super(cause);
    }
}
