// Autogenerated by metajava.py.
// Do not edit this file directly.
// The template for this file is located at:
// ../../../../../../../templates/Exception.java
package com.rethinkdb;

public class ReqlResourceLimitError extends ReqlRuntimeError {
    public ReqlResourceLimitError() {}

    public ReqlResourceLimitError(String message) {
        super(message);
    }

    public ReqlResourceLimitError(String format, Object... args) {
        super(String.format(format, args));
    }

    public ReqlResourceLimitError(String message, Throwable cause) {
        super(message, cause);
    }

    public ReqlResourceLimitError(Throwable cause) {
        super(cause);
    }
}
