// Copyright 2010-2014 RethinkDB, all rights reserved.
#include "clustering/administration/jobs/backend.hpp"

#include <set>

#include "clustering/administration/datum_adapter.hpp"
#include "clustering/administration/jobs/manager.hpp"
#include "clustering/administration/jobs/report.hpp"
#include "clustering/administration/main/watchable_fields.hpp"
#include "concurrency/cross_thread_signal.hpp"

// Extends the `job_report_t` with a `std::set<server_id_t>` servers, and the duration
// will be treated as the maximum duration.
class extended_job_report_t : public job_report_t {
public:
    extended_job_report_t(job_report_t const & job_report) : job_report_t(job_report) { }

    std::set<server_id_t> servers;
};

jobs_artificial_table_backend_t::jobs_artificial_table_backend_t(
        mailbox_manager_t *_mailbox_manager,
        const clone_ptr_t<watchable_t<change_tracking_map_t<
            peer_id_t, cluster_directory_metadata_t> > > &_directory_view)
    : mailbox_manager(_mailbox_manager),
      directory_view(_directory_view) {
}

std::string jobs_artificial_table_backend_t::get_primary_key_name() {
    return "id";
}

bool jobs_artificial_table_backend_t::read_all_rows_as_vector(
        signal_t *interruptor,
        std::vector<ql::datum_t> *rows_out,
        UNUSED std::string *error_out) {
    rows_out->clear();

    cross_thread_signal_t ct_interruptor(interruptor, home_thread());
    on_thread_t rethreader(home_thread());

    std::map<uuid_u, extended_job_report_t> extended_reports;

    typedef std::map<peer_id_t, cluster_directory_metadata_t> peers_t;
    peers_t peers = directory_view->get().get_inner();
    pmap(peers.begin(), peers.end(), [&](peers_t::value_type const &peer) {
        cond_t got_reports;
        disconnect_watcher_t disconnect_watcher(mailbox_manager, peer.first);

        mailbox_t<void(std::vector<job_report_t>)> return_mailbox(
            mailbox_manager,
            [&](UNUSED signal_t *, std::vector<job_report_t> const &reports) {
                for (auto const &report : reports) {
                    auto result = extended_reports.insert(
                        std::make_pair(report.id, extended_job_report_t(report)));

                    // Note `std::map.insert` returns a `std::pair<iterator, bool>`,
                    // here we update the `extended_report_t` regardless of the success.
                    result.first->second.duration =
                        std::max(result.first->second.duration, report.duration);
                    result.first->second.servers.insert(peer.second.server_id);
                }

                got_reports.pulse();
            });
        send(mailbox_manager,
             peer.second.jobs_mailbox.get_job_reports_mailbox_address,
             return_mailbox.get_address());

        wait_any_t waiter(&got_reports, &disconnect_watcher);
        wait_interruptible(&waiter, &ct_interruptor);
    });

    for (auto const &report : extended_reports) {
        ql::datum_object_builder_t builder;
        builder.overwrite("id", convert_uuid_to_datum(report.first));
        builder.overwrite("servers", convert_set_to_datum<server_id_t>(
            convert_uuid_to_datum, report.second.servers));
        builder.overwrite("type", convert_string_to_datum(report.second.type));
        if (report.second.duration >= 0) {
            builder.overwrite(
                "duration", ql::datum_t(report.second.duration / 1000000));  // microseconds -> seconds
        }
        rows_out->push_back(std::move(builder).to_datum());
    }

    return true;
}

bool jobs_artificial_table_backend_t::read_row(UNUSED ql::datum_t primary_key,
                                               UNUSED signal_t *interruptor,
                                               ql::datum_t *row_out,
                                               UNUSED std::string *error_out) {
    on_thread_t rethreader(home_thread());
    *row_out = ql::datum_t();

    return true;
}

bool jobs_artificial_table_backend_t::write_row(UNUSED ql::datum_t primary_key,
                                                UNUSED bool pkey_was_autogenerated,
                                                UNUSED ql::datum_t *new_value_inout,
                                                UNUSED signal_t *interruptor,
                                                std::string *error_out) {
    error_out->assign("It's illegal to write to the `rethinkdb.jobs` table.");
    return false;
}

