package com.rethinkdb.response;

import com.rethinkdb.proto.ResponseType;
import com.rethinkdb.proto.ResponseNote;
import com.rethinkdb.RethinkDBException;
import com.rethinkdb.ast.Query;
import org.json.simple.*;

import java.util.*;
import java.nio.ByteBuffer;
import java.io.ByteArrayInputStream;
import java.io.InputStreamReader;
import java.util.stream.Collectors;

public class Response {
    public final long token;
    public final ResponseType type;
    public final ArrayList<ResponseNote> notes;
    public final Optional<JSONObject> data;
    public final Optional<Profile> profile;
    public final Optional<Backtrace> backtrace;

    public static Response parseFrom(long token, byte[] buf) {
        InputStreamReader codepointReader =
            new InputStreamReader(new ByteArrayInputStream(buf), "UTF-8");
        JSONObject jsonResp = (JSONObject) JSONValue.parse(codepointReader);
        ResponseType responseType = ResponseType.fromValue((int)jsonResp.get("t"));
        ArrayList<Integer> responseNoteVals = (ArrayList) jsonResp
            .getOrDefault("n", new ArrayList());
        ArrayList<ResponseNote> responseNotes = responseNoteVals
            .stream()
            .map(ResponseNote::fromValue)
            .collect(Collectors.toCollection(ArrayList::new));
        return new Response(token, responseType, responseNotes,
                            Optional.empty(), Optional.empty());
    }

    public Response(long token,
                    ResponseType responseType,
                    ArrayList<ResponseNote> responseNotes,
                    Optional<Profile> profile,
                    Optional<Backtrace> backtrace
                    ) {
        this.token = token;
        this.type = responseType;
        this.notes = responseNotes;
        this.profile = profile;
        this.backtrace = backtrace;
    }

    public RethinkDBException makeError(Query query) {
        throw new RuntimeException("makeError not implemented");
    }

    public boolean isWaitComplete() {
        return type == ResponseType.WAIT_COMPLETE;
    }

    /* Whether the response is any kind of feed */
    public boolean isFeed() {
        return notes.stream().allMatch(ResponseNote::isFeed);
    }

    /* Whether the response is any kind of error */
    public boolean isError() {
        return type.isError();
    }

    /* Autogenerated methods below */

    /* What type of success the response contains */
    % for success_type in proto['Response']['ResponseType'].keys():
        % if success_type.startswith('SUCCESS_'):
    public boolean ${"is"+camel(success_type[8:])}() {
        return type == ResponseType.${success_type};
    }
        % endif
    % endfor
}
