#!/usr/bin/python
from plot import *
import sys
if len(sys.argv) != 2:
    print "Usage: %s %s" % (sys.argv[0], 'file-to-parse')
    exit(2)
r = DriveStats()
r.read(sys.argv[1])
r.json('drive_timeseries', '')

with open('stats', 'w') as outf:
    for column in r.stats().iteritems():
        print >>outf, "%s:\n\tMean: %d\n\tstdev %d\n" % (column[0], column[1]['mean'], column[1]['stdev'])

for ts in r.data.iteritems():
    r.data[ts[0]] = ts[1][int(len(ts) * .7) :]

with open('steady_stats', 'w') as outf:
    for column in r.stats().iteritems():
        print >>outf, "%s:\n\tMean: %d\n\tstdev %d\n" % (column[0], column[1]['mean'], column[1]['stdev'])
