=head1 NAME

libmemcachedutil - Utility library for libmemcached

=head1 LIBRARY

C Client Library containing utility functions for libmemcached (libmemcachedutil, -lmemcachedutil)

=head1 SYNOPSIS

  cc [ flag ... ] file ... -lmemcachedutil

  #include <libmemcached/memcached_util.h>

=head1 DESCRIPTION

B<libmemcachedutil> is a small and thread-safe client library that provides
extra functionality built on top of B<libmemcached>.

=head1 THREADS

Do not try to access an instance of C<memcached_st> from multiple threads
at the same time. If you want to access memcached from multiple threads
you should either clone the C<memcached_st>, or use the memcached pool
implementation. see memcached_pool_create(3).

=head1 HOME

To find out more information please check:
L<https://launchpad.net/libmemcached>

=head1 AUTHOR

Trond Norbye, E<lt>trond.norbye@gmail.comE<gt>

=head1 SEE ALSO

libmemcached(3) memcached_pool_create(3) memcached_pool_destroy(3) memcached_pool_pop(3) memcached_pool_push(3)

=cut
