=head1 NAME

memflush - Reset a server or list of servers

=head1 SYNOPSIS

  memflush [options]

=head1 DESCRIPTION

B<memflush> resets the contents of memcached(1) servers.
This means all data in these servers will be deleted.

You can specify servers via the B<--servers> option or via the
environment variable C<MEMCACHED_SERVERS>.

For a full list of operations run the tool with the B<--help> option.

=head1 HOME

To find out more information please check:
L<https://launchpad.net/libmemcached>

=head1 AUTHOR

Brian Aker, E<lt>brian@tangent.orgE<gt>

Mark Atwood E<lt>mark@fallenpegasus.comE<gt>

=head1 SEE ALSO

memcached(1) libmemcached(3)

=cut

