#!/bin/bash

# This workload uses a customized stress client, which constantly runs exactly one rget at a time.

if [ $DATABASE == "rethinkdb" ]; then
    ./dbench                                                                                      \
        -d "$BENCH_DIR/bench_output/Canonical_plus_huge_range_scans" -H $SERVER_HOSTS    \
        {server}rethinkdb:"--active-data-extents 1 -c 12 -m 32768 $SSD_DRIVES --unsaved-data-limit 32768"                                            \
        {client}stress[$RGET_STRESS_CLIENT]:"-w special_rget_scan_workload"\
        iostat:1 vmstat:1 rdbstat:1
elif [ $DATABASE == "mysql" ]; then
    ./dbench                                                                                   \
        -d "$BENCH_DIR/bench_output/Canonical_plus_huge_range_scans" -H $SERVER_HOSTS             \
        {server}mysql:"$MYSQL_COMMON_FLAGS $MYSQL_BUFFER_FLAGS $MYSQL_DURABILITY_FLAGS $MYSQL_SSD_FLAGS"              \
        {client}mysqlstress[$RGET_STRESS_CLIENT]:"-w special_rget_scan_workload" \
        iostat:1 vmstat:1
else
    echo "No workload configuration for $DATABASE"
fi

