#!/bin/bash

mkdir -p "$BENCH_DIR/bench_output/Canonical_plus_range_scans"
. `dirname "$0"`/DESCRIPTION_RUN > "$BENCH_DIR/bench_output/Canonical_plus_range_scans/DESCRIPTION_RUN"

if [ $DATABASE == "rethinkdb" ]; then
    . `dirname "$0"`/DESCRIPTION > "$BENCH_DIR/bench_output/Canonical_plus_range_scans/DESCRIPTION"
fi
