#!/bin/bash

# SSD I/O bound performance

if [ $DATABASE == "rethinkdb" ]; then
    ./dbench                                                                \
        -d "$BENCH_DIR/bench_output/SSD_IO_performance" -H magneto,magneto2 \
        {server}rethinkdb:"-c 12 -m 64 $SSD_DRIVES"                          \
        {client}stress[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'         \
        iostat:1 vmstat:1 rdbstat:1
elif [ $DATABASE == "mysql" ]; then
    ./dbench                                                                \
        -d "$BENCH_DIR/bench_output/SSD_IO_performance" -H 10.0.0.2         \
        {server}mysql:"$MYSQL_COMMON_FLAGS --innodb_buffer_pool_size=64m $MYSQL_DURABILITY_FLAGS"  \
        {client}mysqlstress[dr-doom:/home/teapot/stress]:'-c 128 -d 60s'    \
        iostat:1 vmstat:1
else
    echo "No workload configuration for $DATABASE"
fi
