#!/bin/bash

#mkdir -p "$BENCH_DIR/bench_output/Zynga_workload"
#. `dirname "$0"`/DESCRIPTION_RUN > "$BENCH_DIR/bench_output/Zynga_workload/DESCRIPTION_RUN"

#if [ $DATABASE == "rethinkdb" ]; then
    #. `dirname "$0"`/DESCRIPTION > "$BENCH_DIR/bench_output/Zynga_workload/DESCRIPTION"
#fi

