#!/bin/bash

# Set up the directory
BENCH_DIR="$HOME/bench/$(date +%Y-%m-%d-%H:%M)"
mkdir -p "$BENCH_DIR"
rm -f $HOME/bench/latest
ln -s $BENCH_DIR $HOME/bench/latest
#exec > "$BENCH_DIR/full_bench.log" 2>&1


# Horrible but working way of finding the argument after --email.
email="$(perl -e 'use List::Util qw(first); my $email_idx = 1 + first { $ARGV[$_] eq "--email" } 0 .. $#ARGV; print $ARGV[$email_idx]' -- "$@")"

# Build the server and the stress client
cd src
make clean
make -j DEBUG=0 VALGRIND=0
cd ../bench/stress-client
make
scp stress dr-doom:/home/teapot/stress
cd ../dbench

# Some helper functions
function delete_database_files() { # They are large and useless.
    rm -f "$(find "$BENCH_DIR" -name rethinkdb_data)"
}

# Set up the SSDs as individual devices, and note their names to pass to rethinkdb.
SSD_DRIVES="$(sudo /usr/local/bin/raidconfig ssd single | sed 's/^/-f /; s/$/ /' | tr -d '\n')"


# Canonical workload on the canonical setup
../../build/release/rethinkdb --create $SSD_DRIVES --force
./dbench                                                                                      \
    -d "$BENCH_DIR/bench_output/Canonical_workload_on_canonical_hardware" -H magneto,magneto2 \
    {server}rethinkdb:"-c 12 -m 32768 $SSD_DRIVES"                                            \
    {client}stressfree[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'                           \
    iostat:1 vmstat:1 rdbstat:1

# Out of RAM performance
# SSD I/O bound performance
../../build/release/rethinkdb --create $SSD_DRIVES --force
./dbench                                                                \
    -d "$BENCH_DIR/bench_output/SSD_IO_performance" -H magneto,magneto2 \
    {server}rethinkdb:"-c 12 -m 0 $SSD_DRIVES"                          \
    {client}stressfree[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'     \
    iostat:1 vmstat:1 rdbstat:1

# Store keys in temporary file.
TMP_KEY_FILE="$(ssh dr-doom mktemp)"

# Pure inserts performance
../../build/release/rethinkdb --create $SSD_DRIVES --force
./dbench                                                                                        \
    -d "$BENCH_DIR/bench_output/Pure_inserts_on_canonical_hardware" -H magneto,magneto2         \
    {server}rethinkdb:"-c 12 -m 32768 $SSD_DRIVES"                                              \
    {client}stressfree[dr-doom:/home/teapot/stress]:"-c 512 -w 0/0/1/0 -o $TMP_KEY_FILE -d 60s" \
    iostat:1 vmstat:1 rdbstat:1

# Pure selects performance (run right after insert without recreating the database)
./dbench                                                                                        \
    -d "$BENCH_DIR/bench_output/Pure_selects_on_canonical_hardware" -H magneto,magneto2         \
    {server}rethinkdb:"-c 12 -m 32768 $SSD_DRIVES"                                              \
    {client}stressfree[dr-doom:/home/teapot/stress]:"-c 512 -w 0/0/0/1 -i $TMP_KEY_FILE -d 60s" \
    iostat:1 vmstat:1 rdbstat:1

# Delete temporary key file.
ssh dr-doom -- rm "$TMP_KEY_FILE"

# Core/CPU scalability
# Concurrent clients scalability
# Canonical workload on HDD performance

# Durability settings performance
../../build/release/rethinkdb --create $SSD_DRIVES --force
./dbench                                                                              \
    -d "$BENCH_DIR/bench_output/Strong_durability_performance" -H magneto,magneto2    \
    {server}rethinkdb:"--wait-for-flush y --flush-timer 2 -c 12 -m 32768 $SSD_DRIVES" \
    {client}stressfree[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'                   \
    iostat:1 vmstat:1 rdbstat:1

# Now that all benchmarks are done, delete any database files that might have been left over
delete_database_files

# OProfile example
#./dbench -d  "$BENCH_DIR/prof_output"     -H magneto,magneto2 {server}rethinkdb:'-c 12 -s 128' {client}stressfree[dr-doom:/home/teapot/stress]:'-c 512 -d 10000000'             iostat:1 vmstat:1 rdbstat:1 oprofile
#delete_database_files

# Generate statistics and email.
cd ../format
./report.py "$BENCH_DIR" "$email" > "$BENCH_DIR/report.log" 2>&1

