#!/bin/bash

# Set up the directory
BENCH_DIR="$HOME/bench/$(date +%Y-%m-%d-%H:%M)"
mkdir -p "$BENCH_DIR"
rm -f $HOME/bench/latest
ln -s $BENCH_DIR $HOME/bench/latest
#exec > "$BENCH_DIR/full_bench.log" 2>&1


# Horrible but working way of finding the argument after --email.
# TODO
email="$(perl -e 'use List::Util qw(first); my $email_idx = 1 + first { $ARGV[$_] eq "--email" } 0 .. $#ARGV; print $ARGV[$email_idx]' -- "$@")"

# Build the server and the stress client
cd src
make clean
make -j DEBUG=0 VALGRIND=0 FAST_PERFMON=1 # TODO: Disable "FAST" Perfmon?
cd ../bench/stress-client
make
scp stress dr-doom:/home/teapot/stress
cd ../dbench

# Some helper functions
function delete_database_files() { # They are large and useless.
    rm -f "$(find "$BENCH_DIR" -name rethinkdb_data)"
}

# Set up the SSDs as individual devices, and note their names to pass to rethinkdb.
#SSD_DRIVES="$(sudo /usr/local/bin/raidconfig ssd single | sed 's/^/-f /; s/$/ /' | tr -d '\n')"
SSD_DRIVES="-f /dev/sdb -f /dev/sdc -f /dev/sdd -f /dev/sde"
HDD_DRIVES="" # TODO


# Run workloads
for WORKLOAD in ../workloads/*; do
    if [ -d "$WORKLOAD" ]; then
        echo -e "\E[37;44m\033[1mRunning workload in $WORKLOAD\033[0m"
        export BENCH_DIR
        export SSD_DRIVES
        export HDD_DRIVES
    
        if [ -e "$WORKLOAD/Setup" ]; then
            "$WORKLOAD/Setup"
        fi
        
        for CONFIGURATION in $( find "$WORKLOAD" -type f -name "R*" | sort ); do
            echo -e "\033[1mRunning $CONFIGURATION\033[0m"
            if [ -e "$BENCH_DIR/environment" ]; then
                `cat $BENCH_DIR/environment`
            fi
            $CONFIGURATION
        done
        
        if [ -e "$WORKLOAD/Teardown" ]; then
            if [ -e "$BENCH_DIR/environment" ]; then
                `cat $BENCH_DIR/environment`
            fi
            "$WORKLOAD/Teardown"
        fi
        
        rm -f "$BENCH_DIR/environment"
    fi
done

# TODO:
# Core/CPU scalability
# Concurrent clients scalability
# Canonical workload on HDD performance


# Now that all benchmarks are done, delete any database files that might have been left over
delete_database_files

# OProfile example
#./dbench -d  "$BENCH_DIR/prof_output"     -H magneto,magneto2 {server}rethinkdb:'-c 12 -s 128' {client}stress[dr-doom:/home/teapot/stress]:'-c 512 -d 10000000'             iostat:1 vmstat:1 rdbstat:1 oprofile
#delete_database_files

# Generate statistics and email.
cd ../format
./report.py "$BENCH_DIR" "$email" > "$BENCH_DIR/report.log" 2>&1

