#!/usr/bin/env python

import os, time, random, string, contextlib
import flask
import simple_linear_db, json, zipfile, tarfile, tempfile

assert __name__ == "__main__"

app = flask.Flask(__name__)

def generate_subbable_link(page, **kwargs):
    """generate_subbable_link(page, **kwargs) -> URL containing substitutions

This is best explained by example. Suppose you have the following Flask rule:

    @app.route("/foo/<foo>/bar/<bar>/baz")
    def blah(foo, bar):
        ...

Then `generate_subbable_link("blah", foo="<FOO>", bar="<BAR>")` will return
something like `"http://.../foo/<FOO>/bar/<BAR>/baz"`.

The use case for this is when Javascript needs to be able to generate URLs for
Flask routes. You can write Python code like this:

    my_js = '''
    var my_foo = somehow_get_foo_id();
    var my_bar = somehow_get_bar_id();
    var url = %s.replace("<FOO>", my_foo).replace("<BAR>", my_bar);
    do_something_with(url);
    ''' % json.dumps(generate_subbable_link("blah", foo="<FOO>", bar="<BAR>"))

Note that if the substitution is not surrounded by angle brackets, then it will
be escaped.
    """
    magics = { }
    non_magics = { }
    for key in kwargs:
        if kwargs[key].startswith("<") and kwargs[key].endswith(">"):
            s = ""
            for i in xrange(10):
                s += random.choice(string.letters)
            magics[key] = s
        else:
            non_magics[key] = kwargs[key]
    all_subs = magics.copy()
    all_subs.update(non_magics)
    url = flask.url_for(page, **all_subs)
    for key in magics:
        assert url.count(magics[key]) == 1
        url = url.replace(magics[key], kwargs[key])
    return url

shared_javascript = r"""
function isEmpty(x) {
    for (var i in x) {
        return false;
    }
    return true;
};

function doGET(url, cb) {
    var req = new XMLHttpRequest();
    req.open('GET', url, true);
    req.onreadystatechange = function (e) {
        if (req.readyState === 4) { // Completed
            if (req.status == 200) {
                cb(req);
            } else {
                console.log("HTTP request to", url, "status code", req.status);
            }
        }
    };
    req.send(null);
}

function parseJSON(json) {
    if (json === '') {
        throw "Empty JSON response"
    }
    try {
        return eval('(' + json + ')');
    } catch (e) {
        console.log(json);
        throw e;
    }
}

function doGETJSON(url, cb) {
    doGET(url, function (req) {
        cb(parseJSON(req.responseText));
    });
}

function currentUnixTimestamp() {
    return (new Date()).getTime() / 1000;
}

var formatDuration = function(seconds) {
    function pad(s) {
        s = "" + s;
        if (s.length == 1) {
            s = "0" + s;
        }
        return s;
    }
    var s = Math.floor(seconds % 60);
    var m = Math.floor(seconds / 60) % 60;
    var h = Math.floor(seconds / 3600);
    return '' + pad(h) + ':' + pad(m) + ':' + pad(s);
};


function makeElement(tag, style, children) {
    var e = document.createElement(tag);
    for (var name in style) {
        e.style[name] = style[name];
    }
    if (children) {
        children.forEach(function (c) {
            e.appendChild(c);
        });
    }
    return e;
}

function makeText(text) {
    return document.createTextNode(text);
}

function makeLink(href, children) {
    var e = document.createElement("a");
    e.href = href;
    if (children) {
        children.forEach(function (c) {
            e.appendChild(c);
        });
    }
    return e;
}

function OptionalRenderer(name, subRendererFunc) {
    this.element = makeElement("div", { }, []);
    this.setData = function (data) {
        if (data !== undefined) {
            if (this.header === undefined) {
                this.header = makeElement("h2", { }, [makeText(name + ":")]);
                this.renderer = subRendererFunc();
                this.element.appendChild(this.header);
                this.element.appendChild(this.renderer.element);
            }
            this.renderer.setData(data);
        } else {
            if (this.header !== undefined) {
                this.element.removeChild(this.header);
                this.element.removeChild(this.renderer.element);
                this.header = this.renderer = undefined;
            }
        }
    };
}

function CountedTableRenderer(headers, rowRendererFunc, labels, labelFunc) {
    this.countRenderer = new CountRenderer(labels, labelFunc);
    this.sortedTableRenderer = new SortedTableRenderer(headers, rowRendererFunc);
    this.element = makeElement("div", { }, [
        makeElement("p", { }, [
            this.countRenderer.element
        ]),
        this.sortedTableRenderer.element
    ]);
    this.setData = function (data) {
        this.countRenderer.setData(data);
        this.sortedTableRenderer.setData(data);
    };
};

function SortedTableRenderer(headers, rowRendererFunc) {
    this.tableRenderer = new TableRenderer(headers, rowRendererFunc);
    this.element = this.tableRenderer.element;
    this.setData = function (data) {
        var keys = [];
        for (var name in data) {
            keys.push(name);
        }
        keys.sort(function(x, y) {
            var xi = parseInt(x);
            var yi = parseInt(y);
            if (isNaN(xi) && isNaN(yi)) {
                return (x > y) ? 1 : (x < y) ? -1 : 0;
            } else if (isNaN(xi)) {
                return -1;
            } else if (isNaN(yi)) {
                return 1;
            } else {
                return (xi > yi) ? 1 : (xi < yi) ? -1 : 0;
            }
            });
        this.tableRenderer.setOrder([]);
        this.tableRenderer.setObjects(data);
        this.tableRenderer.setOrder(keys);
    };
};

function TableRenderer(headers, rowRendererFunc) {
    this.tbody = makeElement("tbody", { }, []);
    this.element = makeElement("table", { }, [
        makeElement("thead", { }, [
            makeElement("tr", { }, headers.map(function (name) {
                return makeElement("th", { }, [makeText(name)]);
            }))
        ]),
        this.tbody
    ]);
    this.rowRenderers = { };
    this.objects = { };
    this.order = [];
    this.setObjects = function (objects) {
        var this_ = this;
        this.objects = objects;
        this.order.forEach(function (name) {
            this_.rowRenderers[name].setData(this_.objects[name]);
        });
    };
    this.setOrder = function (newOrder) {
        var this_ = this;
        this.order.forEach(function (name) {
            this_.tbody.removeChild(this_.rowRenderers[name].element);
        });
        newRowRenderers = { };
        newOrder.forEach(function (name) {
            if (this_.rowRenderers[name] !== undefined) {
                newRowRenderers[name] = this_.rowRenderers[name];
            } else {
                newRowRenderers[name] = rowRendererFunc(name);
                newRowRenderers[name].setData(this_.objects[name]);
            }
        });
        this.rowRenderers = newRowRenderers;
        this.order = newOrder;
        this.order.forEach(function (name) {
            this_.tbody.appendChild(this_.rowRenderers[name].element);
        });
    };
};

function BuildStatusRenderer() {
    this.element = makeElement("span", { }, []);
    this.setData = function(build) {
        if (build.status == "waiting") {
            this.element.style.color = "black";
            this.element.textContent = "Waiting";
        } else if (build.status == "uploading") {
            this.element.style.color = "#CCAA00";
            this.element.textContent = "Uploading";
        } else if (build.status == "running") {
            this.element.style.color = "#CCAA00";
            this.element.textContent = "Running (" + formatDuration(currentUnixTimestamp() - build.start_time) + ")";
        } else if (build.status == "ok") {
            this.element.style.color = "green";
            this.element.textContent = "OK (" + formatDuration(build.end_time - build.start_time) + ")";
        } else if (build.status == "fail") {
            this.element.style.color = "#CC0000";
            this.element.textContent = "Fail (" + formatDuration(build.end_time - build.start_time) + ")";
        } else if (build.status == "bug") {
            this.element.style.color = "#CC0000";
            this.element.textContent = "Bug";
        }
    };
};

function TestRoundStatusRenderer() {
    this.element = makeElement("span", { }, []);
    this.setData = function(round) {
        if (round.status == "waiting") {
            this.element.style.color = "black";
            this.element.textContent = "Waiting";
        } else if (round.status == "running") {
            this.element.style.color = "#CCAA00";
            this.element.textContent = "Running (" + formatDuration(currentUnixTimestamp() - round.start_time) + ")";
        } else if (round.status == "pass") {
            this.element.style.color = "green";
            this.element.textContent = "Pass (" + formatDuration(round.end_time - round.start_time) + ")";
        } else if (round.status == "fail") {
            this.element.style.color = "#CC0000";
            this.element.textContent = "Fail (" + formatDuration(round.end_time - round.start_time) + ")";
        } else if (round.status == "bug") {
            this.element.style.color = "#CC0000";
            this.element.textContent = "Bug";
        }
    };
};

function TestStatusRenderer(url_pattern) {
    this.element = makeElement("span", { }, []);
    this.setData = function (test) {
        if (test.rounds === undefined && this.roundRenderers !== undefined) {
            this.roundBits.forEach(this.element.removeChild);
            this.roundRenderers = undefined;
            this.roundBits = undefined;
        }
        if (test.missing === undefined && this.missingText !== undefined) {
            this.element.removeChild(this.missingText);
            this.missingText = undefined;
        }
        if (test.rounds !== undefined) {
            if (this.roundRenderers === undefined) {
                this.roundRenderers = { };
                this.roundBits = [];
                for (var i in test.rounds) {
                    this.roundRenderers[i] = new TestRoundStatusRenderer();
                    if (i != 0) {
                        var comma = makeText(", ");
                        this.roundBits.push(comma);
                        this.element.appendChild(comma);
                    }
                    var link = makeLink(url_pattern.replace("<ROUND>", i), [this.roundRenderers[i].element]);
                    this.roundBits.push(link);
                    this.element.appendChild(link);
                }
            }
            for (var i in test.rounds) {
                this.roundRenderers[i].setData(test.rounds[i]);
            }
        }
        if (test.missing !== undefined) {
            if (this.missingText === undefined) {
                this.missingText = makeText("Missing prerequisites");
                this.element.appendChild(this.missingText);
            }
        }
    };
};

function CountRenderer(labels, classifier) {
    this.element = makeElement("span", { }, []);
    this.setData = function (data) {
        var counts = { };
        labels.forEach(function (label) {
            counts[label] = 0;
        });
        for (var key in data) {
            var classification = classifier(data[key]);
            counts[classification] += 1;
        }
        var text = "";
        labels.forEach(function (label) {
            if (counts[label] != 0) {
                if (text != "") {
                    text += " - ";
                }
                text += counts[label] + " " + label;
            }
        });
        this.element.textContent = text;
    };
};

function LongTextRenderer(height) {
    var text = document.createTextNode();
    this.element = makeElement("textarea", { "width": "70%", "height": height + "px", "whitespace": "pre", "font-family": "monospace" }, []);
    this.element.readOnly = true;
    this.element.wrap = "off";
    this.setData = function (output) {
        this.element.textContent = output;
    };
};
"""

@app.route("/raw/results")
def raw_list_results():
    results = simple_linear_db.read_linear_db("result_log.txt")
    return json.dumps(results)

@app.route("/raw/output")
def raw_list_output():
    with open("output.txt") as output_file:
        return json.dumps(output_file.read())

@app.route("/raw/failures.tar.gz")
def raw_failures():
    def wsgi_dumper_app(environ, start_response):
        results = simple_linear_db.read_linear_db("result_log.txt")
        filenames = []
        for test_id, test in results["tests"].iteritems():
            if "rounds" in test:
                for round_id, round in test["rounds"].iteritems():
                    if round["status"] == "fail":
                        filenames.extend([
                            os.path.join(test_id, str(round_id), "output.txt"),
                            os.path.join(test_id, str(round_id), "output_from_test.zip")
                            ])
        tarball_contents_directory = "failures-%s" % time.strftime("%Y-%m-%d", time.gmtime(os.stat("result_log.txt").st_ctime))
        with tempfile.TemporaryFile() as tarball_temp_file:
            with contextlib.closing(tarfile.open(mode = "w:gz", fileobj = tarball_temp_file)) as tarball_writer:
                for filename in filenames:
                    tarball_writer.add(
                        os.path.join("tests", filename),
                        arcname = os.path.join(tarball_contents_directory, filename)
                        )
            start_response("200 OK", [("Content-Type", "application/x-tar/gz")])
            tarball_temp_file.seek(0)
            while True:
                block = tarball_temp_file.read(4096)
                if not block:
                    break
                yield block
    return wsgi_dumper_app

@app.route("/")
def list():
    template = r"""
        <html>
            <head>
                <title>Nightly test</title>
                <script type="text/javascript">
                    %(shared_javascript)s

                    function ListRootRenderer() {
                        this.buildsRenderer = new OptionalRenderer(
                            "Builds",
                            function () {
                                return new SortedTableRenderer(
                                    ["Build", "Status"],
                                    function (name) {
                                        return new BuildRowRenderer(name);
                                    }
                                );
                            }
                        );
                        this.testsRenderer = new OptionalRenderer(
                            "Tests",
                            function () {
                                return new TestsRenderer();
                            }
                        );
                        this.logRenderer = new OptionalRenderer(
                            "Log",
                            function () {
                                return new LongTextRenderer(800);
                            }
                        );
                        this.element = makeElement("div", { }, [
                            this.buildsRenderer.element,
                            this.testsRenderer.element,
                            this.logRenderer.element
                        ]);
                        this.setResults = function (results) {
                            this.buildsRenderer.setData(results.builds);
                            this.testsRenderer.setData(results.tests);
                        };
                        this.setOutput = function (output) {
                            this.logRenderer.setData(output);
                        };
                    };

                    function TestsRenderer() {
                        this.countedTableRenderer = new CountedTableRenderer(
                            ["Test", "Command line", "Status"],
                            function (name) {
                                return new TestRowRenderer(name);
                            },
                            ["missing prerequisites", "waiting", "running", "passed", "failed", "mixed", "bugs"],
                            function (test) {
                                if (test.missing) {
                                    return "missing prerequisites";
                                }
                                var statuses = { };
                                for (var key in test.rounds) {
                                    statuses[test.rounds[key].status] = true;
                                }
                                if (statuses["running"] !== undefined) {
                                    return "running";
                                } else if (statuses["waiting"] !== undefined) {
                                    return "waiting";
                                } else if (statuses["bug"] !== undefined) {
                                    return "bug";
                                } else if (statuses["pass"] !== undefined && statuses["fail"] === undefined) {
                                    return "passed";
                                } else if (statuses["pass"] === undefined && statuses["fail"] !== undefined) {
                                    return "failed";
                                } else if (statuses["pass"] !== undefined && statuses["fail"] !== undefined) {
                                    return "mixed";
                                }
                            }
                        );
                        this.element = makeElement("div", { }, [
                            makeElement("p", { }, [
                                makeText("Command to automatically download failures: "),
                                makeElement("code", { }, [
                                    makeText("curl -f " + %(failures_url)s + " | tar -xzf -")
                                ])
                            ]),
                            this.countedTableRenderer.element
                        ]);
                        this.setData = function (data) {
                            this.countedTableRenderer.setData(data);
                        }
                    }

                    function BuildRowRenderer(name) {
                        this.statusRenderer = new BuildStatusRenderer();
                        this.element = makeElement("tr", { }, [
                            makeElement("td", { }, [
                                makeLink(%(build_url_pattern)s.replace("<BUILD>", name), [
                                    makeText(name)
                                ])
                            ]),
                            makeElement("td", { }, [this.statusRenderer.element])
                        ]);
                        this.setData = function (build) {
                            this.statusRenderer.setData(build);
                        };
                    };

                    function TestRowRenderer(name) {
                        this.statusRenderer = new TestStatusRenderer(%(round_url_pattern)s.replace("<TEST>", name));
                        this.commandLineText = makeText("");
                        var commandLineTd = makeElement("td", { }, []);
                        this.element = makeElement("tr", { }, [
                            makeElement("td", { }, [
                                makeLink(%(test_url_pattern)s.replace("<TEST>", name), [
                                    makeText(name)
                                ]),
                            ]),
                            commandLineTd,
                            makeElement("td", { }, [this.statusRenderer.element])
                        ]);
                        this.setData = function (test) {
                            this.statusRenderer.setData(test);
                            commandLineTd.textContent = test.command_line;
                        };
                    };

                    function refresh() {
                        console.log("refresh()");
                        doGETJSON(%(refresh_results_url)s, function (results) {
                            console.log("got results", results);
                            root.setResults(results);
                        });
                        doGETJSON(%(refresh_output_url)s, function (output) {
                            console.log("got output");
                            root.setOutput(output);
                        });
                    }

                    initialResults = %(initial_results)s;
                    initialOutput = %(initial_output)s;
                    function start() {
                        console.log("start()");
                        root = new ListRootRenderer();
                        root.setResults(initialResults);
                        root.setOutput(initialOutput);
                        document.getElementsByTagName("body")[0].appendChild(root.element);
                        setInterval("refresh()", 1000);
                    };
                </script>
            </head>
            <body onload="start();">
                <h1>Nightly test</h1>
            </body>
        </html>
    """
    return template % {
        "shared_javascript": shared_javascript,
        "initial_results": raw_list_results(),
        "refresh_results_url": json.dumps(flask.url_for("raw_list_results")),
        "initial_output": raw_list_output(),
        "refresh_output_url": json.dumps(flask.url_for("raw_list_output")),
        "build_url_pattern": json.dumps(generate_subbable_link("build", name="<BUILD>")),
        "test_url_pattern": json.dumps(generate_subbable_link("test", name="<TEST>")),
        "round_url_pattern": json.dumps(generate_subbable_link("round", name="<TEST>", round="<ROUND>")),
        "failures_url": json.dumps(flask.url_for("raw_failures", _external = True))
        }

@app.route("/raw/build/<name>/results")
def raw_build_results(name):
    results = simple_linear_db.read_linear_db("result_log.txt")
    if "builds" not in results or name not in results["builds"]:
        flask.abort(404)
    return json.dumps(results["builds"][name])

@app.route("/raw/build/<name>/output")
def raw_build_output(name):
    if os.path.exists("builds/%s.txt" % name):
        with open("builds/%s.txt" % name) as output_file:
            return json.dumps(output_file.read())
    else:
        return "undefined"

@app.route("/build/<name>/")
def build(name):
    template = r"""
        <html>
            <head>
                <title>Build: %(name)s</title>
                <script type="text/javascript">
                    %(shared_javascript)s

                    function BuildRootRenderer(name) {
                        this.statusRenderer = new BuildStatusRenderer();
                        this.tracebackRenderer = new OptionalRenderer(
                            "Traceback",
                            function () {
                                return new LongTextRenderer(400);
                            }
                        );
                        this.logRenderer = new OptionalRenderer(
                            "Log",
                            function () {
                                return new LongTextRenderer(800);
                            }
                        );
                        this.element = makeElement("div", { }, [
                            makeElement("p", { }, [
                                makeText("Status: "),
                                this.statusRenderer.element
                            ]),
                            this.tracebackRenderer.element,
                            this.logRenderer.element
                        ]);
                        this.setResult = function (build) {
                            this.statusRenderer.setData(build);
                            this.tracebackRenderer.setData(build.traceback);
                        };
                        this.setOutput = function (output) {
                            this.logRenderer.setData(output);
                        };
                    }

                    function refresh() {
                        doGETJSON(%(refresh_result_url)s, function (result) {
                            root.setResult(result);
                        });
                        doGETJSON(%(refresh_output_url)s, function (output) {
                            root.setOutput(output);
                        });
                    }

                    initialResult = %(initial_result)s;
                    initialOutput = %(initial_output)s;
                    function start() {
                        root = new BuildRootRenderer();
                        root.setResult(initialResult);
                        root.setOutput(initialOutput);
                        document.getElementsByTagName("body")[0].appendChild(root.element);
                        setInterval("refresh()", 1000);
                    }
                </script>
            </head>
            <body onload="start();">
                <h1>Build: %(name)s</h1>
            </body>
        </html>
        """
    return template % {
        "shared_javascript": shared_javascript,
        "name": flask.escape(name),
        "initial_result": raw_build_results(name),
        "refresh_result_url": json.dumps(flask.url_for("raw_build_results", name=name)),
        "initial_output": raw_build_output(name),
        "refresh_output_url": json.dumps(flask.url_for("raw_build_output", name=name))
        }

@app.route("/raw/test/<name>/result")
def raw_test_result(name):
    results = simple_linear_db.read_linear_db("result_log.txt")
    if "tests" not in results or name not in results["tests"]:
        flask.abort(404)
    return json.dumps(results["tests"][name])

@app.route("/test/<name>/")
def test(name):
    template = r"""
        <html>
            <head>
                <title>Test: %(name)s</title>
                <script type="text/javascript">
                    %(shared_javascript)s

                    function TestRootRenderer() {
                        this.statusRenderer = new TestStatusRenderer(%(round_url_pattern)s);
                        var commandLineNode = makeElement("code", { }, [])
                        this.missingRenderer = new OptionalRenderer(
                            "Missing prerequisites",
                            function () {
                                return new ListRenderer();
                            }
                        );
                        this.element = makeElement("div", { }, [
                            makeElement("p", { }, [
                                makeText("Command line: "),
                                commandLineNode
                            ]),
                            makeElement("p", { }, [
                                makeText("Status: "),
                                this.statusRenderer.element
                            ]),
                            this.missingRenderer.element
                        ]);
                        this.setResult = function (test) {
                            this.statusRenderer.setData(test);
                            commandLineNode.textContent = test.command_line;
                            this.missingRenderer.setData(test.missing);
                        };
                    }

                    function ListRenderer() {
                        this.element = makeElement("ul", { }, []);
                        this.things = [];
                        this.setData = function (data) {
                            var this_ = this;
                            this.things.forEach(this.element.removeChild);
                            this.things = [];
                            data.forEach(function (thing) {
                                var el = makeElement("li", { }, [makeText(thing)]);
                                this_.element.appendChild(el);
                                this_.things.push(el);
                            });
                        };
                    }

                    function refresh() {
                        doGETJSON(%(refresh_result_url)s, function (result) {
                            root.setResult(result);
                        });
                    }

                    initialResult = %(initial_result)s;
                    function start() {
                        root = new TestRootRenderer();
                        root.setResult(initialResult);
                        document.getElementsByTagName("body")[0].appendChild(root.element);
                        setInterval("refresh()", 1000);
                    };
                </script>
            </head>
            <body onload="start();">
                <h1>Test: %(name)s</h1>
            </body>
        </html>
        """
    return template % {
        "shared_javascript": shared_javascript,
        "name": flask.escape(name),
        "initial_result": raw_test_result(name),
        "refresh_result_url": json.dumps(flask.url_for("raw_test_result", name=name)),
        "round_url_pattern": json.dumps(generate_subbable_link("round", name=name, round="<ROUND>"))
        }

@app.route("/raw/test/<name>/round/<round>/results")
def raw_test_round_result(name, round):
    results = simple_linear_db.read_linear_db("result_log.txt")
    if "tests" not in results or name not in results["tests"] or \
            "rounds" not in results["tests"][name] or int(round) not in results["tests"][name]["rounds"]:
        flask.abort(404)
    return json.dumps(results["tests"][name]["rounds"][int(round)])

@app.route("/raw/test/<name>/round/<round>/output")
def raw_test_round_output(name, round):
    file_path = "tests/%s/%s/output.txt" % (name, round)
    if os.path.exists(file_path):
        stats = os.stat(file_path)
        if stats.st_size < 500 * 1024:
            with open(file_path) as output_file:
                return json.dumps(output_file.read())
        else:
            return json.dumps("(output omitted because it's %d bytes)" % stats.st_size)
    else:
        return json.dumps("(output file missing)")

@app.route("/raw/test/<name>/round/<round>/files/")
def raw_test_round_files(name, round):
    results = simple_linear_db.read_linear_db("result_log.txt")
    if "tests" not in results or name not in results["tests"] or \
            "rounds" not in results["tests"][name] or int(round) not in results["tests"][name]["rounds"]:
        flask.abort(404)
    result = results["tests"][name]["rounds"][int(round)]
    if result["status"] not in ("pass", "fail"):
        return json.dumps(None)
    with contextlib.closing(zipfile.ZipFile(os.path.join("tests", name, round, "output_from_test.zip"))) as output_from_test:
        file_descriptions = { }
        for info in output_from_test.infolist():
            is_directory = info.filename.endswith("/")
            path_parts = info.filename.rstrip("/").split("/")
            assert path_parts[0] == "output_from_test"
            path_parts = path_parts[1:]
            if len(path_parts) != 1:
                continue
            if is_directory:
                file_description = {
                    "type": "directory"
                    }
            else:
                with contextlib.closing(output_from_test.open(info)) as fileobj:
                    sample_size = 100
                    sample = fileobj.read(sample_size)
                    # If the file is not human-readable, don't include it in the
                    # output
                    if all(x in string.printable for x in sample):
                        # If the file is too big, don't include it in the output
                        max_size = 20 * 1024 * 1024
                        if info.file_size < max_size:
                            file_description = {
                                "type": "normal",
                                "contents": sample + fileobj.read()
                                }
                        else:
                            file_description = {
                                "type": "too_big",
                                "size": info.file_size
                                }
                    else:
                        file_description = {
                            "type": "binary",
                            "size": info.file_size
                            }
            file_descriptions[info.filename] = file_description
    return json.dumps(file_descriptions)

@app.route("/raw/test/<name>/round/<round>/files/<path:path>")
def raw_test_round_file_dump(name, round, path):
    def wsgi_dumper_app(environ, start_response):
        with contextlib.closing(zipfile.ZipFile(os.path.join("tests", name, round, "output_from_test.zip"))) as output_from_test:
            try:
                info = output_from_test.getinfo(path)
            except KeyError:
                start_response("404 Not Found", [])
            else:
                start_response("200 OK", [("Content-Length", str(info.file_size))])
                with contextlib.closing(output_from_test.open(info)) as fileobj:
                    while True:
                        block = fileobj.read(4096)
                        if not block:
                            break
                        yield block
    return wsgi_dumper_app

@app.route("/test/<name>/round/<round>/")
def round(name, round):
    template = r"""
        <html>
            <head>
                <title>Test: %(name)s (round %(round)s)</title>
                <script type="text/javascript">
                    %(shared_javascript)s

                    function TestRoundRootRenderer(name) {
                        this.statusRenderer = new TestRoundStatusRenderer();
                        var commandLineNode = makeElement("code", { }, [])
                        this.tracebackRenderer = new OptionalRenderer(
                            "Traceback",
                            function () {
                                return new LongTextRenderer(400);
                            }
                        );
                        this.logRenderer = new OptionalRenderer(
                            "Log",
                            function () {
                                return new LongTextRenderer(400);
                            }
                        );
                        this.filesRenderer = new FilesRenderer();
                        this.element = makeElement("div", { }, [
                            makeElement("p", { }, [
                                makeText("Command line: "),
                                commandLineNode
                            ]),
                            makeElement("p", { }, [
                                makeText("Status: "),
                                this.statusRenderer.element
                            ]),
                            this.tracebackRenderer.element,
                            this.logRenderer.element,
                            this.filesRenderer.element
                        ]);
                        this.setResult = function (round) {
                            this.statusRenderer.setData(round);
                            this.tracebackRenderer.setData(round.traceback);
                        };
                        this.setTestData = function (test) {
                            commandLineNode.textContent = test.command_line;
                        };
                        this.setOutput = function (output) {
                            this.logRenderer.setData(output);
                        };
                        this.setFiles = function (files) {
                            this.filesRenderer.setData(files);
                        };
                    };

                    function FilesRenderer() {
                        this.element = makeElement("div", { }, []);
                        this.blocks = [];
                        this.setData = function (file_descriptions) {
                            var this_ = this;
                            this.blocks.forEach(function (block) {
                                this_.element.removeChild(block);
                            });
                            this.blocks = [];
                            for (var name in file_descriptions) {
                                var file = file_descriptions[name];
                                var element;
                                if (file.type != "directory") {
                                    var subelement;
                                    if (file.type == "normal") {
                                        var renderer = new LongTextRenderer(200);
                                        renderer.setData(file.contents);
                                        subelement = renderer.element;
                                    } else if (file.type == "too_big") {
                                        subelement = makeText("Too big to display (" + file.size + " bytes)");
                                    } else if (file.type == "binary") {
                                        subelement = makeText("Binary file (" + file.size + " bytes)");
                                    }
                                    element = makeElement("div", { }, [
                                        makeElement("p", { }, [
                                            makeLink(%(dump_url_pattern)s.replace("<PATH>", name), [
                                                makeText("Download")
                                            ])
                                        ]),
                                        subelement
                                    ]);
                                } else {
                                    element = makeText("Directory");
                                }
                                var block = makeElement("div", { }, [
                                    makeElement("h2", { }, [
                                        makeElement("code", { }, [
                                            makeText(name)
                                        ])
                                    ]),
                                    element
                                ]);
                                this.blocks.push(block);
                                this_.element.appendChild(block);
                            }
                        };
                    };

                    function refresh() {
                        doGETJSON(%(refresh_result_url)s, function (result) {
                            root.setResult(result);
                            if (result.status == "pass" || result.status == "fail" || result.status == "bug") {
                                cancelInterval(theRefreshTimer);
                            }
                        });
                        doGETJSON(%(refresh_output_url)s, function (output) {
                            root.setOutput(output);
                        });
                        doGETJSON(%(refresh_files_url)s, function (files) {
                            root.setFiles(files);
                        });
                    }

                    initialResult = %(initial_result)s;
                    initialTestData = %(initial_test_data)s;
                    initialOutput = %(initial_output)s;
                    initialFiles = %(initial_files)s;
                    function start() {
                        root = new TestRoundRootRenderer();
                        root.setResult(initialResult);
                        root.setTestData(initialTestData);
                        root.setOutput(initialOutput);
                        root.setFiles(initialFiles);
                        document.getElementsByTagName("body")[0].appendChild(root.element);
                        if (!(initialResult.status == "pass" || initialResult.status == "fail" || initialResult.status == "bug")) {
                            theRefreshTimer = setInterval("refresh()", 1000);
                        }
                    };
                </script>
            </head>
            <body onload="start();">
                <h1>Test: %(name)s (round %(round)s)</h1>
            </body>
        </html>
        """
    return template % {
        "shared_javascript": shared_javascript,
        "name": flask.escape(name),
        "round": flask.escape(round),
        "initial_result": raw_test_round_result(name, round),
        "refresh_result_url": json.dumps(flask.url_for("raw_test_round_result", name=name, round=round)),
        "initial_test_data": raw_test_result(name),
        "initial_output": raw_test_round_output(name, round),
        "refresh_output_url": json.dumps(flask.url_for("raw_test_round_output", name=name, round=round)),
        "initial_files": raw_test_round_files(name, round),
        "refresh_files_url": json.dumps(flask.url_for("raw_test_round_files", name=name, round=round)),
        "dump_url_pattern": json.dumps(generate_subbable_link("raw_test_round_file_dump", name=name, round=round, path="<PATH>"))
        }

app.debug = True

from wsgiref.handlers import CGIHandler
CGIHandler().run(app)
