#!/bin/bash

mkdir -p $BENCH_DIR/bench_output/Number_of_clients_on_canonical_hardware_select_only_workload
echo Clients > $BENCH_DIR/bench_output/Number_of_clients_on_canonical_hardware_select_only_workload/multirun

# Fake a 0-clients result for nicer graphs
mkdir -p $BENCH_DIR/bench_output/Number_of_clients_on_canonical_hardware_select_only_workload/0/1/client
echo -e "1\t\t0" > $BENCH_DIR/bench_output/Number_of_clients_on_canonical_hardware_select_only_workload/0/1/client/qps.txt

if [ $DATABASE == "membase" ]; then
    export PERSISTENT_DATA_DIR="$BENCH_DIR/membase_data_persistent"
fi

# Store keys in temporary file.
export TMP_KEY_FILE="$(ssh puzzler mktemp)"

export -p > "$BENCH_DIR/environment"

