#!/bin/bash

mkdir -p "$BENCH_DIR/bench_output/Canonical_workload_with_large_values_(4K-64K)"
. `dirname "$0"`/DESCRIPTION_RUN > "$BENCH_DIR/bench_output/Canonical_workload_with_large_values_(4K-64K)/DESCRIPTION_RUN"

if [ $DATABASE == "rethinkdb" ]; then
    . `dirname "$0"`/DESCRIPTION > "$BENCH_DIR/bench_output/Canonical_workload_with_large_values_(4K-64K)/DESCRIPTION"
    ../../build/release/rethinkdb create $SSD_DRIVES --force
fi
