#!/bin/bash

# Canonical workload on the canonical setup

./dbench                                                                                      \
    -d "$BENCH_DIR/bench_output/Canonical_workload_on_canonical_hardware" -H magneto,magneto2 \
    {server}rethinkdb:"-c 12 -m 32768 $SSD_DRIVES"                                            \
    {client}stress[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'                               \
    iostat:1 vmstat:1 rdbstat:1
