#!/bin/bash

mkdir -p "$BENCH_DIR/bench_output/Canonical_workload_on_canonical_hardware"
. `dirname "$0"`/DESCRIPTION_RUN > "$BENCH_DIR/bench_output/Canonical_workload_on_canonical_hardware/DESCRIPTION_RUN"

if [ $DATABASE == "rethinkdb" ]; then
    . `dirname "$0"`/DESCRIPTION > "$BENCH_DIR/bench_output/Canonical_workload_on_canonical_hardware/DESCRIPTION"
fi
