language: node_js
node_js:
  - 0.8
  - 0.10

env:
  - OPTIONALS=Y
  - OPTIONALS=N

install:
  - if [[ "$OPTIONALS" == "Y" ]]; then npm install; fi
  - if [[ "$OPTIONALS" == "N" ]]; then npm install --no-optional; fi
