#!/bin/bash

# We need our git-test
export PATH=$PATH:/usr/local/bin/

# Go into var rethinkdb directory
cd /var/git/rethinkdb/

# Pull latest from master
git pull

# Run the tests
export RETESTER_EMAIL_SENDER=buildbot@rethinkdb.com:allspark
git test -b --revision HEAD --email all@rethinkdb.com --file /var/www/code.rethinkdb.com/htdocs/tests.html test/full_test.py

