#!/bin/bash

BREAKOUT_FILE_NAME=~/nightly_bench_running

# Don't start the test if it's running already
if [ -f $BREAKOUT_FILE_NAME ]
then
exit
fi

# Create the breakout file
touch $BREAKOUT_FILE_NAME

# We need our git-test
export PATH=$PATH:/usr/local/bin/

# Go into var rethinkdb directory
cd /var/git/rethinkdb/

# Pull latest from master
git pull

# Run the tests
# Email is hard-wired for now.
git test -l --email all@rethinkdb.com --revision HEAD bench/full_bench

# Remove the breakout file
rm -f $BREAKOUT_FILE_NAME

