#!/bin/bash

# This is a simple script to launch a rethinkdb python test with valgrind to provide some common arguments such as suppressions and leak checking

valgrind_options="--leak-check=full --track-origins=yes"

raw_rdb_dir="`dirname $0`/.."
rdb_dir=`readlink -f $raw_rdb_dir`
valgrind_suppress="--suppressions=$rdb_dir/scripts/python-valgrind-suppressions.supp --suppressions=$rdb_dir/scripts/rethinkdb-valgrind-suppressions.supp"

if [ $# -lt 1 ]; then
    echo "specify a test to run"
else
    # skip the 'ps' process which is sometimes run by certain tests
    valgrind $valgrind_options $valgrind_suppress --trace-children=yes --trace-children-skip=/bin/ps python $*
fi
