#!/bin/bash

# Pure inserts performance

if [ $DATABASE == "rethinkdb" ]; then
    ./dbench                                                                                        \
        -d "$BENCH_DIR/bench_output/Pure_inserts_on_canonical_hardware" -H $SERVER_HOSTS            \
        {server}rethinkdb:"-c 12 -m 32768 $SSD_DRIVES"                                              \
        {client}stress[dr-doom:/home/teapot/stress]:"-c $CANONICAL_CLIENTS -d $CANONICAL_DURATION -w 0/0/1/0 -o $TMP_KEY_FILE"     \
        iostat:1 vmstat:1 rdbstat:1
elif [ $DATABASE == "mysql" ]; then
    ./dbench                                                                                         \
        -d "$BENCH_DIR/bench_output/Pure_inserts_on_canonical_hardware" -H $SERVER_HOSTS             \
        {server}mysql:"$MYSQL_COMMON_FLAGS $MYSQL_BUFFER_FLAGS $MYSQL_DURABILITY_FLAGS  $MYSQL_SSD_FLAGS"              \
        {client}mysqlstress[dr-doom:/home/teapot/stress]:"-c $CANONICAL_CLIENTS -d $CANONICAL_DURATION -w 0/0/1/0 -o $TMP_KEY_FILE" \
        iostat:1 vmstat:1
else
    echo "No workload configuration for $DATABASE"
fi
