#!/bin/bash

if [ $DATABASE == "rethinkdb" ]; then
    ../../build/release/rethinkdb create $SSD_DRIVES --force
fi

if [ $DATABASE == "membase" ]; then
    export PERSISTENT_DATA_DIR="$BENCH_DIR/membase_data_persistent"
fi

# Store keys in temporary file.
export TMP_KEY_FILE="$(ssh puzzler mktemp)"

export -p > "$BENCH_DIR/environment"
