#!/bin/bash

if [ $DATABASE == "rethinkdb" ]; then
    ../../build/release/rethinkdb --create $SSD_DRIVES --force
fi

# Store keys in temporary file.
export TMP_KEY_FILE="$(ssh dr-doom mktemp)"

export -p > "$BENCH_DIR/environment"
