#!/bin/bash

# Durability settings performance

if [ $DATABASE == "rethinkdb" ]; then
    ./dbench                                                                              \
        -d "$BENCH_DIR/bench_output/Strong_durability_performance" -H magneto,magneto2    \
        {server}rethinkdb:"--wait-for-flush y --flush-timer 2 -c 12 -m 32768 $SSD_DRIVES" \
        {client}stress[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'                       \
        iostat:1 vmstat:1 rdbstat:1
elif [ $DATABASE == "mysql" ]; then
    # TODO: Does it make sense to use just 128 clients here?
    ./dbench                                                                              \
        -d "$BENCH_DIR/bench_output/Strong_durability_performance" -H 10.0.0.2 \
        {server}mysql:"$MYSQL_COMMON_FLAGS $MYSQL_BUFFER_FLAGS --innodb_flush_log_at_trx_commit=1 --innodb_doublewrite=1 --innodb_log_file_size=256m"   \
        {client}mysqlstress[dr-doom:/home/teapot/stress]:'-c 128 -d 60s'                  \
        iostat:1 vmstat:1
else
    echo "No workload configuration for $DATABASE"
fi
