#!/bin/bash

# Durability settings performance
./dbench                                                                              \
    -d "$BENCH_DIR/bench_output/Strong_durability_performance" -H magneto,magneto2    \
    {server}rethinkdb:"--wait-for-flush y --flush-timer 2 -c 12 -m 32768 $SSD_DRIVES" \
    {client}stress[dr-doom:/home/teapot/stress]:'-c 512 -d 60s'                       \
    iostat:1 vmstat:1 rdbstat:1
