#!/bin/bash

if [ $DATABASE == "rethinkdb" ]; then
    ../../build/release/rethinkdb --create $SSD_DRIVES --force
elif [ $DATABASE == "mysql" ]; then
    # Initialize InnoDB RAW tablespace
    /usr/local/mysql/libexec/mysqld $MYSQL_COMMON_FLAGS $MYSQL_BUFFER_FLAGS --innodb_flush_log_at_trx_commit=1 --innodb_doublewrite=1 --innodb_log_file_size=256m" $MYSQL_SSD_CREATE_FLAGS --port=9874 &
    # Wait for server to finish initialization and shut it down
    while ! /usr/local/mysql/bin/mysqladmin shutdown -u root --port=9874 2> /dev/null; do
        sleep 5
    done
fi
