#!/bin/bash

if [ $DATABASE == "rethinkdb" ]; then
    # Recover head stress client
    ssh puzzler mv -f /home/teapot/stress-head /home/teapot/stress
    rm -rf /tmp/baseline-git
    git checkout master
fi
