#!/bin/bash

mkdir -p "$BENCH_DIR/bench_output/Baseline_performance"
. `dirname "$0"`/DESCRIPTION_RUN > "$BENCH_DIR/bench_output/Baseline_performance/DESCRIPTION_RUN"

if [ $DATABASE == "rethinkdb" ]; then
    . `dirname "$0"`/DESCRIPTION > "$BENCH_DIR/bench_output/Baseline_performance/DESCRIPTION"
fi

if [ $DATABASE == "rethinkdb" ]; then
    # Recover head stress client
    #ssh puzzler mv -f /home/teapot/stress-head /home/teapot/stress
    rm -rf /tmp/baseline-git
    git checkout master
fi
