#!/bin/bash

if [ $DATABASE == "rethinkdb" ]; then
    ../../build/release/rethinkdb create $SSD_DRIVES_2 --force
    ./dbench                                                                                      \
        -d "$BENCH_DIR/bench_output/Number_of_SSD/2" -H $SERVER_HOSTS    \
        {server}rethinkdb:"-c 12 -m 32768 $SSD_DRIVES_2"                                            \
        {client}stress[$STRESS_CLIENT]:"-c $CANONICAL_CLIENTS -d $CANONICAL_DURATION" \
        iostat:1 vmstat:1 rdbstat:1
else
    echo "No workload configuration for $DATABASE"
fi

