#!/bin/bash

mkdir -p $BENCH_DIR/bench_output/Number_of_SSD_64MB_cache_canonical_workload
echo Number of SSDs > $BENCH_DIR/bench_output/Number_of_SSD_64MB_cache_canonical_workload/multirun


export SSD_DRIVES_1="-f /dev/sdf"
export SSD_DRIVES_2="-f /dev/sdf -f /dev/sdh"
export SSD_DRIVES_3="-f /dev/sdf -f /dev/sdg -f /dev/sdh"
export SSD_DRIVES_4="-f /dev/sdf -f /dev/sdg -f /dev/sdh -f /dev/sdi"

export -p > "$BENCH_DIR/environment"
