#!/usr/bin/env python
import sys
import subprocess
import getopt
import signal
import pexpect

def main():
    args = " ".join(sys.argv[1:])
    rethinkdb = pexpect.spawn("./rethinkdb " + args)
    rethinkdb.logfile_read = sys.stdout
    try:
        rethinkdb.expect("Server started")
    except pexpect.EOF:
        sys.exit(-1)

    port = "8080"
    opts, extra = getopt.getopt(sys.argv[1:], "p:", "port=")
    if len(opts) > 0:
        port = opts[0][1]

    print "Connecting with telnet: (server will be shut down if this session ends)\n"
    telnet = subprocess.Popen("telnet localhost " + port, shell=True)
    telnet.wait()
    rethinkdb.terminate()
    rethinkdb.read()

if __name__ == "__main__":
    main()
