#!/bin/bash

mkdir -p $BENCH_DIR/bench_output/Number_of_clients_on_canonical_hardware_canonical_workload
echo Clients > $BENCH_DIR/bench_output/Number_of_clients_on_canonical_hardware_canonical_workload/multirun

# Fake a 0-clients result for nicer graphs
mkdir -p $BENCH_DIR/bench_output/Number_of_clients_on_canonical_hardware_canonical_workload/0/1/client
echo 0 > $BENCH_DIR/bench_output/Number_of_clients_on_canonical_hardware_canonical_workload/0/1/client/qps.txt

if [ $DATABASE == "rethinkdb" ]; then
    ../../build/release/rethinkdb create $SSD_DRIVES --force
fi
