#!/bin/bash

mkdir -p "$BENCH_DIR/bench_output/Concurrent_clients_(canonical_workload)"
. `dirname "$0"`/DESCRIPTION_RUN > "$BENCH_DIR/bench_output/Concurrent_clients_(canonical_workload)/DESCRIPTION_RUN"

mkdir -p "$BENCH_DIR/bench_output/Concurrent_clients_(canonical_workload)"
echo Clients > "$BENCH_DIR/bench_output/Concurrent_clients_(canonical_workload)/multirun"

# Fake a 0-clients result for nicer graphs
mkdir -p "$BENCH_DIR/bench_output/Concurrent_clients_(canonical_workload)/0/1/client"
echo -e "1\t\t0" > "$BENCH_DIR/bench_output/Concurrent_clients_(canonical_workload)/0/1/client/qps.txt"

if [ $DATABASE == "rethinkdb" ]; then
    . `dirname "$0"`/DESCRIPTION > "$BENCH_DIR/bench_output/Concurrent_clients_(canonical_workload)/DESCRIPTION"
    ../../build/release/rethinkdb create $SSD_DRIVES --force
fi
