'\" t
.\"     Title: rethinkdb 
.\"    Author: Bill Rowan
.\"      Date: 2012/11/08
.\"    Manual: RethinkDB Manual
.\"    Source: RethinkDB 0.1
.\"  Language: English
.\"
.TH "RETHINKDB" "1" "CURRENT_DATE" "RethinkDB SHORT_VERSION" "RethinkDB Manual"
.SH "NAME"
rethinkdb \- an open source distributed database system
.sp
.SH "DESCRIPTION"
.sp
RethinkDB is an open source distributed database system featuring automatic query parallelization, a powerful query language, and friendly administrative tools. Please run \fI\fBrethinkdb\fR \-\-help for full usage information
